-- =============================================
-- Migration SQL pour TOUTES les sous-catégories
-- Généré automatiquement depuis cat_subcat.md
-- À exécuter dans le SQL Editor de Supabase
-- APRÈS avoir exécuté la migration des catégories principales
-- =============================================

-- Total: 1118 sous-catégories

-- =============================================
-- 1. FILTRE (10 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Filtre à huile',
    'Filtre à air',
    'Filtre d''habitacle',
    'Filtre à carburant',
    'Kit de filtres',
    'Filtre à air secondaire',
    'Filtre à air sport',
    'Filtre boite automatique',
    'Filtre hydraulique de direction',
    'Filtre, unité d''alimentation de carburant'
  ]) as name,
  unnest(ARRAY[
    'filtre-filtre-a-huile',
    'filtre-filtre-a-air',
    'filtre-filtre-d-habitacle',
    'filtre-filtre-a-carburant',
    'filtre-kit-de-filtres',
    'filtre-filtre-a-air-secondaire',
    'filtre-filtre-a-air-sport',
    'filtre-filtre-boite-automatique',
    'filtre-filtre-hydraulique-de-direction',
    'filtre-filtre-unite-d-alimentation-de-carburant'
  ]) as slug,
  'filter_list' as icon,
  c.id as parent_id,
  generate_series(1, 10) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'filtre' AND c.parent_id IS NULL;

-- =============================================
-- 2. FREIN (38 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Plaquette de frein',
    'Disque de frein',
    'Étrier de frein',
    'Flexible de frein',
    'Témoin d''usure plaquette de frein',
    'Kit de frein arrière',
    'Mâchoires de frein',
    'Liquide de frein',
    'Tambour de frein',
    'Capteur ABS',
    'Kit de Réparation Étrier de Frein',
    'Câble de Frein à Main',
    'Cylindre De Roue',
    'Mâchoires de Frein à Main',
    'Support d''Étrier De Frein',
    'Maître-Cylindre',
    'Protection de disque de frein',
    'Kit d''accessoires, plaquette de frein à disque',
    'Mastervac',
    'Pompe à Vide de Freinage',
    'Contacteur De Feux Stop',
    'Kit Freins À Tambours',
    'Plaquette de frein sport',
    'Disque de frein sport',
    'Disque de freins de haute performance',
    'Garnitures de freins de haute performance',
    'Kit disque et plaquette de frein',
    'Frein à main',
    'Ajusteur frein à tambour',
    'Piston d''étrier de frein',
    'Vis de disque de frein',
    'Accumulateur de pression, freinage',
    'Pressostat, hydraulique des freins',
    'Répartiteur de frein',
    'Bloc ABS',
    'Relais diode protection systeme abs',
    'Relais, abs',
    'Bague abs'
  ]) as name,
  unnest(ARRAY[
    'frein-plaquette-de-frein',
    'frein-disque-de-frein',
    'frein-etrier-de-frein',
    'frein-flexible-de-frein',
    'frein-temoin-d-usure-plaquette-de-frein',
    'frein-kit-de-frein-arriere',
    'frein-machoires-de-frein',
    'frein-liquide-de-frein',
    'frein-tambour-de-frein',
    'frein-capteur-abs',
    'frein-kit-de-reparation-etrier-de-frein',
    'frein-cable-de-frein-a-main',
    'frein-cylindre-de-roue',
    'frein-machoires-de-frein-a-main',
    'frein-support-d-etrier-de-frein',
    'frein-maitre-cylindre',
    'frein-protection-de-disque-de-frein',
    'frein-kit-d-accessoires-plaquette-de-frein-a-disque',
    'frein-mastervac',
    'frein-pompe-a-vide-de-freinage',
    'frein-contacteur-de-feux-stop',
    'frein-kit-freins-a-tambours',
    'frein-plaquette-de-frein-sport',
    'frein-disque-de-frein-sport',
    'frein-disque-de-freins-de-haute-performance',
    'frein-garnitures-de-freins-de-haute-performance',
    'frein-kit-disque-et-plaquette-de-frein',
    'frein-frein-a-main',
    'frein-ajusteur-frein-a-tambour',
    'frein-piston-d-etrier-de-frein',
    'frein-vis-de-disque-de-frein',
    'frein-accumulateur-de-pression-freinage',
    'frein-pressostat-hydraulique-des-freins',
    'frein-repartiteur-de-frein',
    'frein-bloc-abs',
    'frein-relais-diode-protection-systeme-abs',
    'frein-relais-abs',
    'frein-bague-abs'
  ]) as slug,
  'speed' as icon,
  c.id as parent_id,
  generate_series(1, 38) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'frein' AND c.parent_id IS NULL;

-- =============================================
-- 3. MOTEUR (77 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Bouchon de vidange',
    'Courroie d''alternateur',
    'Joint de cache-culbuteurs',
    'Support moteur',
    'Kit de distribution',
    'Kit de distribution + pompe à eau',
    'Pompe à eau',
    'Carter d''huile',
    'Pompe à huile',
    'Capteur de pression d''huile',
    'Refroidisseur d''huile',
    'Capteur de niveau d''huile',
    'Chaîne de pompe à huile',
    'Joint de refroidisseur d''huile',
    'Tuyau de graissage turbo',
    'Sonde de temperature d''huile',
    'Joint de pompe à huile',
    'Bague d''étanchéité, pompe à huile',
    'Tuyau d''admission pompe à huile',
    'Courroie de distribution',
    'Kit chaîne de distribution',
    'Chaîne de distribution',
    'Électrovanne déphaseur',
    'Galet tendeur de courroie de distribution',
    'Tendeur de chaine de distribution',
    'Poulie déphaseur',
    'Dispositif de réglage électrique d''arbre à cames',
    'Joint de carter de distribution',
    'Poulie renvoi / transmission, courroie de distribution',
    'Pignon de vilebrequin',
    'Carter de distribution',
    'Guide fixe de chaîne de distribution',
    'Tendeur de courroie de distribution',
    'Amortisseur de vibrations courroie de distribution',
    'Jeu de joints d''etanchéité culasse de cylindre',
    'Arbre à came',
    'Culasse',
    'Joint de bouchon de remplissage d''huile',
    'Cache-culbuteur',
    'Support d''arbre à came',
    'Cale de blocage de soupape',
    'Kit de joints de cache culbuteurs',
    'Vanne EGR',
    'Joint de vanne egr',
    'Refroidisseur EGR',
    'Module-EGR',
    'Tuyau reniflard d''huile',
    'Flexible aération de la housse de culasse',
    'Joint de reniflard',
    'Jeu de joints d''etanchéité carter de vilebrequin',
    'Coussinet de vilebrequin',
    'Pochette de joints moteur',
    'Piston',
    'Carter de protection sous moteur',
    'Volant moteur',
    'Poulies de vilebrequin',
    'Vis de volant moteur',
    'Boulon de bielle et écrou',
    'Bielle',
    'Vis de palier de vilebrequin',
    'Coussinet de palier',
    'Arbre intermédiaire et arbre à contrepoids d''équilibrage',
    'Chemises de cylindre',
    'Vilebrequin',
    'Collecteur d''admission',
    'Valve, contrôle d''air-air d''admission',
    'Collecteur d''echappement',
    'Culbuteur',
    'Soupape d''admission',
    'Soupape d''échappement',
    'Guide de soupape / joint / réglage',
    'Joint de queue de soupape',
    'Cache moteur',
    'Segment de piston',
    'Coussinet de bielle',
    'Kit de réparation, ventilation du carter-moteur',
    'Soupape, dégazage du carter'
  ]) as name,
  unnest(ARRAY[
    'moteur-bouchon-de-vidange',
    'moteur-courroie-d-alternateur',
    'moteur-joint-de-cache-culbuteurs',
    'moteur-support-moteur',
    'moteur-kit-de-distribution',
    'moteur-kit-de-distribution-pompe-a-eau',
    'moteur-pompe-a-eau',
    'moteur-carter-d-huile',
    'moteur-pompe-a-huile',
    'moteur-capteur-de-pression-d-huile',
    'moteur-refroidisseur-d-huile',
    'moteur-capteur-de-niveau-d-huile',
    'moteur-chaine-de-pompe-a-huile',
    'moteur-joint-de-refroidisseur-d-huile',
    'moteur-tuyau-de-graissage-turbo',
    'moteur-sonde-de-temperature-d-huile',
    'moteur-joint-de-pompe-a-huile',
    'moteur-bague-d-etancheite-pompe-a-huile',
    'moteur-tuyau-d-admission-pompe-a-huile',
    'moteur-courroie-de-distribution',
    'moteur-kit-chaine-de-distribution',
    'moteur-chaine-de-distribution',
    'moteur-electrovanne-dephaseur',
    'moteur-galet-tendeur-de-courroie-de-distribution',
    'moteur-tendeur-de-chaine-de-distribution',
    'moteur-poulie-dephaseur',
    'moteur-dispositif-de-reglage-electrique-d-arbre-a-cames',
    'moteur-joint-de-carter-de-distribution',
    'moteur-poulie-renvoi-transmission-courroie-de-distribution',
    'moteur-pignon-de-vilebrequin',
    'moteur-carter-de-distribution',
    'moteur-guide-fixe-de-chaine-de-distribution',
    'moteur-tendeur-de-courroie-de-distribution',
    'moteur-amortisseur-de-vibrations-courroie-de-distribution',
    'moteur-jeu-de-joints-d-etancheite-culasse-de-cylindre',
    'moteur-arbre-a-came',
    'moteur-culasse',
    'moteur-joint-de-bouchon-de-remplissage-d-huile',
    'moteur-cache-culbuteur',
    'moteur-support-d-arbre-a-came',
    'moteur-cale-de-blocage-de-soupape',
    'moteur-kit-de-joints-de-cache-culbuteurs',
    'moteur-vanne-egr',
    'moteur-joint-de-vanne-egr',
    'moteur-refroidisseur-egr',
    'moteur-module-egr',
    'moteur-tuyau-reniflard-d-huile',
    'moteur-flexible-aeration-de-la-housse-de-culasse',
    'moteur-joint-de-reniflard',
    'moteur-jeu-de-joints-d-etancheite-carter-de-vilebrequin',
    'moteur-coussinet-de-vilebrequin',
    'moteur-pochette-de-joints-moteur',
    'moteur-piston',
    'moteur-carter-de-protection-sous-moteur',
    'moteur-volant-moteur',
    'moteur-poulies-de-vilebrequin',
    'moteur-vis-de-volant-moteur',
    'moteur-boulon-de-bielle-et-ecrou',
    'moteur-bielle',
    'moteur-vis-de-palier-de-vilebrequin',
    'moteur-coussinet-de-palier',
    'moteur-arbre-intermediaire-et-arbre-a-contrepoids-d-equilibrage',
    'moteur-chemises-de-cylindre',
    'moteur-vilebrequin',
    'moteur-collecteur-d-admission',
    'moteur-valve-controle-d-air-air-d-admission',
    'moteur-collecteur-d-echappement',
    'moteur-culbuteur',
    'moteur-soupape-d-admission',
    'moteur-soupape-d-echappement',
    'moteur-guide-de-soupape-joint-reglage',
    'moteur-joint-de-queue-de-soupape',
    'moteur-cache-moteur',
    'moteur-segment-de-piston',
    'moteur-coussinet-de-bielle',
    'moteur-kit-de-reparation-ventilation-du-carter-moteur',
    'moteur-soupape-degazage-du-carter'
  ]) as slug,
  'build' as icon,
  c.id as parent_id,
  generate_series(1, 77) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'moteur' AND c.parent_id IS NULL;

-- =============================================
-- 4. CARROSSERIE (55 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Rétroviseur',
    'Vérin de coffre',
    'Miroir de rétroviseur',
    'Feu arrière',
    'Phare avant',
    'Pare-choc',
    'Kit de carrosserie',
    'Calandre',
    'Bandeau pare-choc',
    'Renfort de pare choc',
    'Cache crochet de remorquage',
    'Radar de recul',
    'Lame avant',
    'Support de plaque d''immatriculation',
    'Support de radar de recul',
    'Capot',
    'Insonorisant de capot moteur',
    'Serrure de porte',
    'Poignée de porte',
    'Porte arrière',
    'Barillet de porte',
    'Fermeture centralisée',
    'Joint de pare brise',
    'Bouton de verrouillage',
    'Poignée boîte à gant',
    'Serrure de hayon',
    'Réservoir de carburant',
    'Soupape de ventilation de réservoir de carburant',
    'Face avant',
    'Bas de caisse',
    'Support de cric',
    'Panneau latéral',
    'Montant de porte et pare-brise',
    'Train arrière',
    'Logo',
    'Vitre latérale',
    'Panneau arrière',
    'Plancher de carrosserie',
    'Longeron',
    'Fixation de radiateur',
    'Support de batterie',
    'Pare-brise',
    'Lunette arrière',
    'Aile',
    'Élargisseur d''aile',
    'Enjoliveurs de passage de roue',
    'Pare-boue',
    'Baguette de porte',
    'Portière avant et composants',
    'Coffre à bagages',
    'Vérin de capot',
    'Ressort pneumatique, capote',
    'Ressort pneumatique, table pliante',
    'Rétroviseur intérieur',
    'Coque de rétroviseur'
  ]) as name,
  unnest(ARRAY[
    'carrosserie-retroviseur',
    'carrosserie-verin-de-coffre',
    'carrosserie-miroir-de-retroviseur',
    'carrosserie-feu-arriere',
    'carrosserie-phare-avant',
    'carrosserie-pare-choc',
    'carrosserie-kit-de-carrosserie',
    'carrosserie-calandre',
    'carrosserie-bandeau-pare-choc',
    'carrosserie-renfort-de-pare-choc',
    'carrosserie-cache-crochet-de-remorquage',
    'carrosserie-radar-de-recul',
    'carrosserie-lame-avant',
    'carrosserie-support-de-plaque-d-immatriculation',
    'carrosserie-support-de-radar-de-recul',
    'carrosserie-capot',
    'carrosserie-insonorisant-de-capot-moteur',
    'carrosserie-serrure-de-porte',
    'carrosserie-poignee-de-porte',
    'carrosserie-porte-arriere',
    'carrosserie-barillet-de-porte',
    'carrosserie-fermeture-centralisee',
    'carrosserie-joint-de-pare-brise',
    'carrosserie-bouton-de-verrouillage',
    'carrosserie-poignee-boite-a-gant',
    'carrosserie-serrure-de-hayon',
    'carrosserie-reservoir-de-carburant',
    'carrosserie-soupape-de-ventilation-de-reservoir-de-carburant',
    'carrosserie-face-avant',
    'carrosserie-bas-de-caisse',
    'carrosserie-support-de-cric',
    'carrosserie-panneau-lateral',
    'carrosserie-montant-de-porte-et-pare-brise',
    'carrosserie-train-arriere',
    'carrosserie-logo',
    'carrosserie-vitre-laterale',
    'carrosserie-panneau-arriere',
    'carrosserie-plancher-de-carrosserie',
    'carrosserie-longeron',
    'carrosserie-fixation-de-radiateur',
    'carrosserie-support-de-batterie',
    'carrosserie-pare-brise',
    'carrosserie-lunette-arriere',
    'carrosserie-aile',
    'carrosserie-elargisseur-d-aile',
    'carrosserie-enjoliveurs-de-passage-de-roue',
    'carrosserie-pare-boue',
    'carrosserie-baguette-de-porte',
    'carrosserie-portiere-avant-et-composants',
    'carrosserie-coffre-a-bagages',
    'carrosserie-verin-de-capot',
    'carrosserie-ressort-pneumatique-capote',
    'carrosserie-ressort-pneumatique-table-pliante',
    'carrosserie-retroviseur-interieur',
    'carrosserie-coque-de-retroviseur'
  ]) as slug,
  'directions_car' as icon,
  c.id as parent_id,
  generate_series(1, 55) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'carrosserie' AND c.parent_id IS NULL;

-- =============================================
-- 5. SUSPENSION (29 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Bras de suspension',
    'Biellette de barre stabilisatrice',
    'Rotule de suspension',
    'Roulement de roue',
    'Moyeu de roue',
    'Barre stabilisatrice',
    'Kit réparation biellette de barre stabilisatrice',
    'Support, suspension du stabilisateur',
    'Kit réparation suspension de roue',
    'Kit d''assemblage bras de liaison',
    'Vis de réglage du carrossage',
    'Kit réparation rotule de suspension',
    'Rotule de direction',
    'Rotule axiale',
    'Soufflet de direction',
    'Silent bloc de direction',
    'Élargisseur de voie',
    'Support de boite de vitesse',
    'Fusée',
    'Roulement boîtier du roulement des roues',
    'Pivot de fusée',
    'Douille, pivot de direction',
    'Silent bloc d''essieu',
    'Silent bloc de triangle',
    'Kit de réparation de bras de suspension',
    'Poutre d''essieu',
    'Écrou, bout d''essieu',
    'Bague étanchéité roulement avant',
    'Coussinet, fusée d''essieu'
  ]) as name,
  unnest(ARRAY[
    'suspension-bras-de-suspension',
    'suspension-biellette-de-barre-stabilisatrice',
    'suspension-rotule-de-suspension',
    'suspension-roulement-de-roue',
    'suspension-moyeu-de-roue',
    'suspension-barre-stabilisatrice',
    'suspension-kit-reparation-biellette-de-barre-stabilisatrice',
    'suspension-support-suspension-du-stabilisateur',
    'suspension-kit-reparation-suspension-de-roue',
    'suspension-kit-d-assemblage-bras-de-liaison',
    'suspension-vis-de-reglage-du-carrossage',
    'suspension-kit-reparation-rotule-de-suspension',
    'suspension-rotule-de-direction',
    'suspension-rotule-axiale',
    'suspension-soufflet-de-direction',
    'suspension-silent-bloc-de-direction',
    'suspension-elargisseur-de-voie',
    'suspension-support-de-boite-de-vitesse',
    'suspension-fusee',
    'suspension-roulement-boitier-du-roulement-des-roues',
    'suspension-pivot-de-fusee',
    'suspension-douille-pivot-de-direction',
    'suspension-silent-bloc-d-essieu',
    'suspension-silent-bloc-de-triangle',
    'suspension-kit-de-reparation-de-bras-de-suspension',
    'suspension-poutre-d-essieu',
    'suspension-ecrou-bout-d-essieu',
    'suspension-bague-etancheite-roulement-avant',
    'suspension-coussinet-fusee-d-essieu'
  ]) as slug,
  'settings' as icon,
  c.id as parent_id,
  generate_series(1, 29) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'suspension' AND c.parent_id IS NULL;

-- =============================================
-- 6. SYSTÈME D'ESSUIE-GLACES (17 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Essuie-glace',
    'Bras d''essuie-glace',
    'Pompe de lave-glace',
    'Moteur d''essuie-glace',
    'Tringlerie d''essuie-glace',
    'Lame d''essuie-glace',
    'Balai d''essuie-glace, nettoyage des phares',
    'Essuie-glace arrière',
    'Gicleur de lave-glace',
    'Gicleur de lave-phare',
    'Pompe lave phare',
    'Pièce de jonction, tuyauterie d''eau de nettoyage',
    'Capteur, niveau de l''eau de lavage',
    'Contacteur tournant',
    'Relais d''essuie-glace',
    'Capteur de pluie',
    'Lave-glace'
  ]) as name,
  unnest(ARRAY[
    'systeme-d-essuie-glaces-essuie-glace',
    'systeme-d-essuie-glaces-bras-d-essuie-glace',
    'systeme-d-essuie-glaces-pompe-de-lave-glace',
    'systeme-d-essuie-glaces-moteur-d-essuie-glace',
    'systeme-d-essuie-glaces-tringlerie-d-essuie-glace',
    'systeme-d-essuie-glaces-lame-d-essuie-glace',
    'systeme-d-essuie-glaces-balai-d-essuie-glace-nettoyage-des-phares',
    'systeme-d-essuie-glaces-essuie-glace-arriere',
    'systeme-d-essuie-glaces-gicleur-de-lave-glace',
    'systeme-d-essuie-glaces-gicleur-de-lave-phare',
    'systeme-d-essuie-glaces-pompe-lave-phare',
    'systeme-d-essuie-glaces-piece-de-jonction-tuyauterie-d-eau-de-nettoyage',
    'systeme-d-essuie-glaces-capteur-niveau-de-l-eau-de-lavage',
    'systeme-d-essuie-glaces-contacteur-tournant',
    'systeme-d-essuie-glaces-relais-d-essuie-glace',
    'systeme-d-essuie-glaces-capteur-de-pluie',
    'systeme-d-essuie-glaces-lave-glace'
  ]) as slug,
  'water_drop' as icon,
  c.id as parent_id,
  generate_series(1, 17) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'systeme-d-essuie-glaces' AND c.parent_id IS NULL;

-- =============================================
-- 7. AMORTISSEMENT (21 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Amortisseur',
    'Ressort d''amortisseur',
    'Coupelle d''amortisseur',
    'Kit de protection d''amortisseur et butée élastique de suspension',
    'Jeu de ressorts d''amortisseurs',
    'Jambe de suspension',
    'Patin de ressort',
    'Lame de ressort',
    'Suspension de la cabine',
    'Silent bloc d''amortisseur',
    'Support amortisseur',
    'Soufflet à air suspension pneumatique',
    'Suspension pneumatique',
    'Sphère de suspension',
    'Compresseur de suspension pneumatique',
    'Huile hydraulique',
    'Relais, correcteur d''assiette',
    'Ressort court',
    'Kit de suspension, amortisseur et ressort',
    'Suspension sport',
    'Amortisseur de direction'
  ]) as name,
  unnest(ARRAY[
    'amortissement-amortisseur',
    'amortissement-ressort-d-amortisseur',
    'amortissement-coupelle-d-amortisseur',
    'amortissement-kit-de-protection-d-amortisseur-et-butee-elastique-de-suspension',
    'amortissement-jeu-de-ressorts-d-amortisseurs',
    'amortissement-jambe-de-suspension',
    'amortissement-patin-de-ressort',
    'amortissement-lame-de-ressort',
    'amortissement-suspension-de-la-cabine',
    'amortissement-silent-bloc-d-amortisseur',
    'amortissement-support-amortisseur',
    'amortissement-soufflet-a-air-suspension-pneumatique',
    'amortissement-suspension-pneumatique',
    'amortissement-sphere-de-suspension',
    'amortissement-compresseur-de-suspension-pneumatique',
    'amortissement-huile-hydraulique',
    'amortissement-relais-correcteur-d-assiette',
    'amortissement-ressort-court',
    'amortissement-kit-de-suspension-amortisseur-et-ressort',
    'amortissement-suspension-sport',
    'amortissement-amortisseur-de-direction'
  ]) as slug,
  'compress' as icon,
  c.id as parent_id,
  generate_series(1, 21) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'amortissement' AND c.parent_id IS NULL;

-- =============================================
-- 8. ALLUMAGE ET PRÉCHAUFFAGE (17 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Bougie',
    'Bougie de préchauffage',
    'Bobine d''allumage',
    'Faisceau moteur',
    'Tête de delco',
    'Capteur d''arbre à came',
    'Capteur pmh',
    'Doigt d''allumeur',
    'Allumeur et composants',
    'Relais de préchauffage',
    'Module d''allumage',
    'Fiche bougie d''allumage',
    'Capteur de cliquetis',
    'Kit réparation distributeur d''allumage',
    'Chapeau pare-poussière, distributeur d''allumage',
    'Boîte de dépression, distibuteur d''allumage',
    'Bougie de préchauffage, chauffage auxiliaire'
  ]) as name,
  unnest(ARRAY[
    'allumage-et-prechauffage-bougie',
    'allumage-et-prechauffage-bougie-de-prechauffage',
    'allumage-et-prechauffage-bobine-d-allumage',
    'allumage-et-prechauffage-faisceau-moteur',
    'allumage-et-prechauffage-tete-de-delco',
    'allumage-et-prechauffage-capteur-d-arbre-a-came',
    'allumage-et-prechauffage-capteur-pmh',
    'allumage-et-prechauffage-doigt-d-allumeur',
    'allumage-et-prechauffage-allumeur-et-composants',
    'allumage-et-prechauffage-relais-de-prechauffage',
    'allumage-et-prechauffage-module-d-allumage',
    'allumage-et-prechauffage-fiche-bougie-d-allumage',
    'allumage-et-prechauffage-capteur-de-cliquetis',
    'allumage-et-prechauffage-kit-reparation-distributeur-d-allumage',
    'allumage-et-prechauffage-chapeau-pare-poussiere-distributeur-d-allumage',
    'allumage-et-prechauffage-boite-de-depression-distibuteur-d-allumage',
    'allumage-et-prechauffage-bougie-de-prechauffage-chauffage-auxiliaire'
  ]) as slug,
  'flash_on' as icon,
  c.id as parent_id,
  generate_series(1, 17) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'allumage-et-prechauffage' AND c.parent_id IS NULL;

-- =============================================
-- 9. HUILES ET FLUIDES (11 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Huile moteur',
    'Liquide de refroidissement',
    'Liquide de frein',
    'Huile boîte de vitesse',
    'Huile direction assistée',
    'Huile pour boîte de vitesse automatique',
    'Huile hydraulique',
    'AdBlue',
    'Eau distillée',
    'Lave-glace',
    'Antigel'
  ]) as name,
  unnest(ARRAY[
    'huiles-et-fluides-huile-moteur',
    'huiles-et-fluides-liquide-de-refroidissement',
    'huiles-et-fluides-liquide-de-frein',
    'huiles-et-fluides-huile-boite-de-vitesse',
    'huiles-et-fluides-huile-direction-assistee',
    'huiles-et-fluides-huile-pour-boite-de-vitesse-automatique',
    'huiles-et-fluides-huile-hydraulique',
    'huiles-et-fluides-adblue',
    'huiles-et-fluides-eau-distillee',
    'huiles-et-fluides-lave-glace',
    'huiles-et-fluides-antigel'
  ]) as slug,
  'water' as icon,
  c.id as parent_id,
  generate_series(1, 11) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'huiles-et-fluides' AND c.parent_id IS NULL;

-- =============================================
-- 10. COURROIES, CHAÎNES, GALETS (28 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Kit de distribution',
    'Courroie d''alternateur',
    'Kit de distribution + pompe à eau',
    'Kit de courroie d''accessoire',
    'Courroie trapézoïdale',
    'Courroie de distribution',
    'Kit chaîne de distribution',
    'Chaîne de distribution',
    'Galet tendeur de courroie de distribution',
    'Galet tendeur de courroie d''accessoire',
    'Poulie renvoi / transmission, courroie de distribution',
    'Poulie renvoi / transmission, courroie trapézoïdale à nervures',
    'Poulie, courroie de distribution',
    'Poulie-tendeur, courroie trapézoïdale',
    'Tendeur de courroie de distribution',
    'Tendeur de chaine de distribution',
    'Amortisseur de vibrations courroie de distribution',
    'Amortisseur de vibrations courroie trapézoïdale à nervures',
    'Poulie damper',
    'Poulie d''alternateur',
    'Poulie de pompe de direction assistée',
    'Poulie, pompe à eau',
    'Poulie, tendeur de courroie d''accessoire',
    'Vis de poulie de vilebrequin',
    'Manchon flexible d''accouplement',
    'Guide fixe de chaîne de distribution',
    'Joint d''étanchéité tendeur de chaîne de distribution',
    'Chaîne de pompe à huile'
  ]) as name,
  unnest(ARRAY[
    'courroies-chaines-galets-kit-de-distribution',
    'courroies-chaines-galets-courroie-d-alternateur',
    'courroies-chaines-galets-kit-de-distribution-pompe-a-eau',
    'courroies-chaines-galets-kit-de-courroie-d-accessoire',
    'courroies-chaines-galets-courroie-trapezoidale',
    'courroies-chaines-galets-courroie-de-distribution',
    'courroies-chaines-galets-kit-chaine-de-distribution',
    'courroies-chaines-galets-chaine-de-distribution',
    'courroies-chaines-galets-galet-tendeur-de-courroie-de-distribution',
    'courroies-chaines-galets-galet-tendeur-de-courroie-d-accessoire',
    'courroies-chaines-galets-poulie-renvoi-transmission-courroie-de-distribution',
    'courroies-chaines-galets-poulie-renvoi-transmission-courroie-trapezoidale-a-nervures',
    'courroies-chaines-galets-poulie-courroie-de-distribution',
    'courroies-chaines-galets-poulie-tendeur-courroie-trapezoidale',
    'courroies-chaines-galets-tendeur-de-courroie-de-distribution',
    'courroies-chaines-galets-tendeur-de-chaine-de-distribution',
    'courroies-chaines-galets-amortisseur-de-vibrations-courroie-de-distribution',
    'courroies-chaines-galets-amortisseur-de-vibrations-courroie-trapezoidale-a-nervures',
    'courroies-chaines-galets-poulie-damper',
    'courroies-chaines-galets-poulie-d-alternateur',
    'courroies-chaines-galets-poulie-de-pompe-de-direction-assistee',
    'courroies-chaines-galets-poulie-pompe-a-eau',
    'courroies-chaines-galets-poulie-tendeur-de-courroie-d-accessoire',
    'courroies-chaines-galets-vis-de-poulie-de-vilebrequin',
    'courroies-chaines-galets-manchon-flexible-d-accouplement',
    'courroies-chaines-galets-guide-fixe-de-chaine-de-distribution',
    'courroies-chaines-galets-joint-d-etancheite-tendeur-de-chaine-de-distribution',
    'courroies-chaines-galets-chaine-de-pompe-a-huile'
  ]) as slug,
  'settings_ethernet' as icon,
  c.id as parent_id,
  generate_series(1, 28) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'courroies-chaines-galets' AND c.parent_id IS NULL;

-- =============================================
-- 11. SYSTÈME ÉLECTRIQUE (30 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Batterie',
    'Alternateur',
    'Démarreur',
    'Régulateur d''alternateur',
    'Composant alternateur',
    'Poulie d''alternateur',
    'Charbon de démarreur',
    'Interrupteur d''allumage de démarreur',
    'Solénoïde de démarreur',
    'Embrayage à roue libre démarreur',
    'Pièces de démarreur',
    'Relais, démarreur',
    'Fusible',
    'Boîte à fusible',
    'Relais multifonction',
    'Relais de klaxon',
    'Relais de ventilateur',
    'Relais de clim',
    'Relais de siège chauffant',
    'Relais de pompe de gavage',
    'Relais d''essuie-glace',
    'Relais, abs',
    'Relais, chauffage de vitre arrière',
    'Relais, correcteur d''assiette',
    'Relais, verrouillage central',
    'Relais diode protection systeme abs',
    'Jeu de câbles',
    'Faisceau d''attelage',
    'Circuit électrique du moteur',
    'Système électrique central'
  ]) as name,
  unnest(ARRAY[
    'systeme-electrique-batterie',
    'systeme-electrique-alternateur',
    'systeme-electrique-demarreur',
    'systeme-electrique-regulateur-d-alternateur',
    'systeme-electrique-composant-alternateur',
    'systeme-electrique-poulie-d-alternateur',
    'systeme-electrique-charbon-de-demarreur',
    'systeme-electrique-interrupteur-d-allumage-de-demarreur',
    'systeme-electrique-solenoide-de-demarreur',
    'systeme-electrique-embrayage-a-roue-libre-demarreur',
    'systeme-electrique-pieces-de-demarreur',
    'systeme-electrique-relais-demarreur',
    'systeme-electrique-fusible',
    'systeme-electrique-boite-a-fusible',
    'systeme-electrique-relais-multifonction',
    'systeme-electrique-relais-de-klaxon',
    'systeme-electrique-relais-de-ventilateur',
    'systeme-electrique-relais-de-clim',
    'systeme-electrique-relais-de-siege-chauffant',
    'systeme-electrique-relais-de-pompe-de-gavage',
    'systeme-electrique-relais-d-essuie-glace',
    'systeme-electrique-relais-abs',
    'systeme-electrique-relais-chauffage-de-vitre-arriere',
    'systeme-electrique-relais-correcteur-d-assiette',
    'systeme-electrique-relais-verrouillage-central',
    'systeme-electrique-relais-diode-protection-systeme-abs',
    'systeme-electrique-jeu-de-cables',
    'systeme-electrique-faisceau-d-attelage',
    'systeme-electrique-circuit-electrique-du-moteur',
    'systeme-electrique-systeme-electrique-central'
  ]) as slug,
  'electrical_services' as icon,
  c.id as parent_id,
  generate_series(1, 30) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'systeme-electrique' AND c.parent_id IS NULL;

-- =============================================
-- 12. ÉCLAIRAGE ET SIGNALISATION (46 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Phare avant',
    'Feu arrière',
    'Clignotant',
    'Antibrouillard',
    'Feu de position et stationnement',
    'Feu diurne',
    'Feu de recul',
    'Feu de stop',
    'Feu antibrouillard arrière',
    'Feu clignotant latéral',
    '3e feu de stop',
    'Éclairage de plaque d''immatriculation',
    'Éclairage intérieur',
    'Éclairage du coffre',
    'Éclairage de porte',
    'Eclairage des instruments',
    'Ampoule pour feu de croisement',
    'Ampoule feu de route',
    'Ampoule antibrouillard',
    'Ampoule de clignotant',
    'Ampoule de feu arrière',
    'Ampoule feu eclaireur de plaque',
    'Ampoule de feu stop',
    'Ampoule de feu de recul',
    'Phare au xénon',
    'Phare additionnel',
    'Projecteur longue portée',
    'Réglage de phare',
    'Commodo de phare',
    'Centrale clignotant',
    'Contacteur de feux stop',
    'Contacteur de feu de recul',
    'Bouton warning',
    'Contacteur de porte',
    'Interrupteur, feu antibrouillard',
    'Composants des projecteurs principaux',
    'Composants de feu arrière',
    'Composants pour projecteur antibrouillard',
    'Kit de projecteurs principaux',
    'Verre de phare',
    'Catadioptre',
    'Cache antibrouillard',
    'Joint, feu arrière',
    'Gyrophare',
    'Appareil de commande, système d''éclairage',
    'Capteur correcteur d''assiette phare'
  ]) as name,
  unnest(ARRAY[
    'eclairage-et-signalisation-phare-avant',
    'eclairage-et-signalisation-feu-arriere',
    'eclairage-et-signalisation-clignotant',
    'eclairage-et-signalisation-antibrouillard',
    'eclairage-et-signalisation-feu-de-position-et-stationnement',
    'eclairage-et-signalisation-feu-diurne',
    'eclairage-et-signalisation-feu-de-recul',
    'eclairage-et-signalisation-feu-de-stop',
    'eclairage-et-signalisation-feu-antibrouillard-arriere',
    'eclairage-et-signalisation-feu-clignotant-lateral',
    'eclairage-et-signalisation-3e-feu-de-stop',
    'eclairage-et-signalisation-eclairage-de-plaque-d-immatriculation',
    'eclairage-et-signalisation-eclairage-interieur',
    'eclairage-et-signalisation-eclairage-du-coffre',
    'eclairage-et-signalisation-eclairage-de-porte',
    'eclairage-et-signalisation-eclairage-des-instruments',
    'eclairage-et-signalisation-ampoule-pour-feu-de-croisement',
    'eclairage-et-signalisation-ampoule-feu-de-route',
    'eclairage-et-signalisation-ampoule-antibrouillard',
    'eclairage-et-signalisation-ampoule-de-clignotant',
    'eclairage-et-signalisation-ampoule-de-feu-arriere',
    'eclairage-et-signalisation-ampoule-feu-eclaireur-de-plaque',
    'eclairage-et-signalisation-ampoule-de-feu-stop',
    'eclairage-et-signalisation-ampoule-de-feu-de-recul',
    'eclairage-et-signalisation-phare-au-xenon',
    'eclairage-et-signalisation-phare-additionnel',
    'eclairage-et-signalisation-projecteur-longue-portee',
    'eclairage-et-signalisation-reglage-de-phare',
    'eclairage-et-signalisation-commodo-de-phare',
    'eclairage-et-signalisation-centrale-clignotant',
    'eclairage-et-signalisation-contacteur-de-feux-stop',
    'eclairage-et-signalisation-contacteur-de-feu-de-recul',
    'eclairage-et-signalisation-bouton-warning',
    'eclairage-et-signalisation-contacteur-de-porte',
    'eclairage-et-signalisation-interrupteur-feu-antibrouillard',
    'eclairage-et-signalisation-composants-des-projecteurs-principaux',
    'eclairage-et-signalisation-composants-de-feu-arriere',
    'eclairage-et-signalisation-composants-pour-projecteur-antibrouillard',
    'eclairage-et-signalisation-kit-de-projecteurs-principaux',
    'eclairage-et-signalisation-verre-de-phare',
    'eclairage-et-signalisation-catadioptre',
    'eclairage-et-signalisation-cache-antibrouillard',
    'eclairage-et-signalisation-joint-feu-arriere',
    'eclairage-et-signalisation-gyrophare',
    'eclairage-et-signalisation-appareil-de-commande-systeme-d-eclairage',
    'eclairage-et-signalisation-capteur-correcteur-d-assiette-phare'
  ]) as slug,
  'lightbulb' as icon,
  c.id as parent_id,
  generate_series(1, 46) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'eclairage-et-signalisation' AND c.parent_id IS NULL;

-- =============================================
-- 13. REFROIDISSEMENT (41 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Radiateur',
    'Thermostat',
    'Pompe à eau',
    'Vase d''expansion',
    'Durite de refroidissement',
    'Liquide de refroidissement',
    'Sonde de température de liquide de refroidissement',
    'Bouchon liquide de refroidissement',
    'Joint de liquide de refroidissement',
    'Bride de liquide de refroidissement',
    'Embrayage ventilateur de radiateur',
    'Joint de calorstat',
    'Thermocontact de ventilateur',
    'Ventilateur moteur',
    'Bouchon de radiateur',
    'Joint pompe à eau',
    'Capteur niveau liquide de refroidissement',
    'Bouchon de dilatation',
    'Manche, batterie chauffante-chauffage',
    'Pompe à eau additionnelle',
    'Intercooler',
    'Support de radiateur',
    'Gaine, radiateur d''huile de boîte de vitesse',
    'Déflecteur d''air de ventilateur',
    'Hélice du ventilateur de refroidissement moteur',
    'Support, ventilateur de radiateur',
    'Joint collerette de climatisation',
    'Joint d''étanchéité conduit de climatisation',
    'Moteur électrique, ventilateur pour radiateurs',
    'Commande, ventilateur électrique (refroidissement du moteur)',
    'Joint d''étanchéification, conduite de réfrigérant',
    'Rondelle d''étanchéité, bouchon vissable de radiateur',
    'Joint d''etanchéité tuyau de liquide de refroidissement',
    'Bague d''étanchéité, interrupteur de thermostat',
    'Radiateur de chauffage',
    'Refroidisseur d''huile',
    'Joint de refroidisseur d''huile',
    'Thermostat d''huile',
    'Radiateur d''huile de boite de vitesse automatique',
    'Radiateur d''huile, direction',
    'Eau distillée'
  ]) as name,
  unnest(ARRAY[
    'refroidissement-radiateur',
    'refroidissement-thermostat',
    'refroidissement-pompe-a-eau',
    'refroidissement-vase-d-expansion',
    'refroidissement-durite-de-refroidissement',
    'refroidissement-liquide-de-refroidissement',
    'refroidissement-sonde-de-temperature-de-liquide-de-refroidissement',
    'refroidissement-bouchon-liquide-de-refroidissement',
    'refroidissement-joint-de-liquide-de-refroidissement',
    'refroidissement-bride-de-liquide-de-refroidissement',
    'refroidissement-embrayage-ventilateur-de-radiateur',
    'refroidissement-joint-de-calorstat',
    'refroidissement-thermocontact-de-ventilateur',
    'refroidissement-ventilateur-moteur',
    'refroidissement-bouchon-de-radiateur',
    'refroidissement-joint-pompe-a-eau',
    'refroidissement-capteur-niveau-liquide-de-refroidissement',
    'refroidissement-bouchon-de-dilatation',
    'refroidissement-manche-batterie-chauffante-chauffage',
    'refroidissement-pompe-a-eau-additionnelle',
    'refroidissement-intercooler',
    'refroidissement-support-de-radiateur',
    'refroidissement-gaine-radiateur-d-huile-de-boite-de-vitesse',
    'refroidissement-deflecteur-d-air-de-ventilateur',
    'refroidissement-helice-du-ventilateur-de-refroidissement-moteur',
    'refroidissement-support-ventilateur-de-radiateur',
    'refroidissement-joint-collerette-de-climatisation',
    'refroidissement-joint-d-etancheite-conduit-de-climatisation',
    'refroidissement-moteur-electrique-ventilateur-pour-radiateurs',
    'refroidissement-commande-ventilateur-electrique-refroidissement-du-moteur',
    'refroidissement-joint-d-etancheification-conduite-de-refrigerant',
    'refroidissement-rondelle-d-etancheite-bouchon-vissable-de-radiateur',
    'refroidissement-joint-d-etancheite-tuyau-de-liquide-de-refroidissement',
    'refroidissement-bague-d-etancheite-interrupteur-de-thermostat',
    'refroidissement-radiateur-de-chauffage',
    'refroidissement-refroidisseur-d-huile',
    'refroidissement-joint-de-refroidisseur-d-huile',
    'refroidissement-thermostat-d-huile',
    'refroidissement-radiateur-d-huile-de-boite-de-vitesse-automatique',
    'refroidissement-radiateur-d-huile-direction',
    'refroidissement-eau-distillee'
  ]) as slug,
  'ac_unit' as icon,
  c.id as parent_id,
  generate_series(1, 41) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'refroidissement' AND c.parent_id IS NULL;

-- =============================================
-- 14. ÉCHAPPEMENT (31 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Pot d''échappement',
    'Silencieux avant',
    'Silencieux intermédiaire',
    'Tuyau d''échappement',
    'Catalyseur',
    'Filtre à particules (FAP)',
    'Collecteur d''echappement',
    'Embouts d''échappement',
    'Tresse d''échappement',
    'Écran thermique',
    'Clapet de gaz d''échappement',
    'Échappement sport',
    'Silent-bloc d''échappement',
    'Silent-bloc caoutchouc pot d''échappement',
    'Silent-bloc de silencieux arrière',
    'Kit d''assemblage silencieux',
    'Kit d''assemblage catalyseur',
    'Kit de montage collecteur des gaz d''échappement',
    'Kit de montage ligne d''échappement',
    'Collier de serrage d''échappement',
    'Joints de collecteur d''echappement',
    'Joint d''etanchéité tuyau d''echappement',
    'Sonde lambda (NOx)',
    'Capteur de pression des gaz d''echappement',
    'Capteur de température des gaz d''échappement',
    'Pompe d''injection d''air secondaire',
    'Soupape d''air secondaire',
    'Nettoyage du FAP',
    'Module de dosage',
    'Mise à niveau euro1 / euro2',
    'Écran absorbant la chaleur (injection)'
  ]) as name,
  unnest(ARRAY[
    'echappement-pot-d-echappement',
    'echappement-silencieux-avant',
    'echappement-silencieux-intermediaire',
    'echappement-tuyau-d-echappement',
    'echappement-catalyseur',
    'echappement-filtre-a-particules-fap',
    'echappement-collecteur-d-echappement',
    'echappement-embouts-d-echappement',
    'echappement-tresse-d-echappement',
    'echappement-ecran-thermique',
    'echappement-clapet-de-gaz-d-echappement',
    'echappement-echappement-sport',
    'echappement-silent-bloc-d-echappement',
    'echappement-silent-bloc-caoutchouc-pot-d-echappement',
    'echappement-silent-bloc-de-silencieux-arriere',
    'echappement-kit-d-assemblage-silencieux',
    'echappement-kit-d-assemblage-catalyseur',
    'echappement-kit-de-montage-collecteur-des-gaz-d-echappement',
    'echappement-kit-de-montage-ligne-d-echappement',
    'echappement-collier-de-serrage-d-echappement',
    'echappement-joints-de-collecteur-d-echappement',
    'echappement-joint-d-etancheite-tuyau-d-echappement',
    'echappement-sonde-lambda-nox',
    'echappement-capteur-de-pression-des-gaz-d-echappement',
    'echappement-capteur-de-temperature-des-gaz-d-echappement',
    'echappement-pompe-d-injection-d-air-secondaire',
    'echappement-soupape-d-air-secondaire',
    'echappement-nettoyage-du-fap',
    'echappement-module-de-dosage',
    'echappement-mise-a-niveau-euro1-euro2',
    'echappement-ecran-absorbant-la-chaleur-injection'
  ]) as slug,
  'air' as icon,
  c.id as parent_id,
  generate_series(1, 31) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'echappement' AND c.parent_id IS NULL;

-- =============================================
-- 15. CIRCUIT D'ALIMENTATION (35 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Pompe à carburant dans le réservoir',
    'Injecteur',
    'Pompe à injection',
    'Rampe d''injection',
    'Régulateur de pression du carburant',
    'Filtre à carburant',
    'Tuyau de carburant',
    'Réservoir de carburant',
    'Bouchon de réservoir de carburant',
    'Jauge à carburant',
    'Capteur pression de carburant',
    'Capteur température carburant',
    'Joint injecteur',
    'Joint de pompe à carburant',
    'Joint de pompe à injection',
    'Joint d''étanchéité tuyauterie de carburant',
    'Joint d''étanchéité, filtre de carburant',
    'Soupape de filtre à carburant',
    'Filtre, unité d''alimentation de carburant',
    'Pompe de gavage',
    'Relais de pompe de gavage',
    'Accumulateur de pression de carburant',
    'Électrovanne de pompe d''injection',
    'Système d''injection',
    'Kit d''assemblage pompe à carburant',
    'Tuyau, carburant de fuite',
    'Tuyau de ventilation, réservoir de carburant',
    'Soupape de ventilation de réservoir de carburant',
    'Palpeur de niveau, circuit de carburant',
    'Joint d''étanchéité, palpeur de réservoir',
    'Capteur de pression, réservoir de carburant',
    'Composants du carburateur',
    'Semelle de carburateur',
    'Kit de réparation, carburateur',
    'Kit de réparation injecteur'
  ]) as name,
  unnest(ARRAY[
    'circuit-d-alimentation-pompe-a-carburant-dans-le-reservoir',
    'circuit-d-alimentation-injecteur',
    'circuit-d-alimentation-pompe-a-injection',
    'circuit-d-alimentation-rampe-d-injection',
    'circuit-d-alimentation-regulateur-de-pression-du-carburant',
    'circuit-d-alimentation-filtre-a-carburant',
    'circuit-d-alimentation-tuyau-de-carburant',
    'circuit-d-alimentation-reservoir-de-carburant',
    'circuit-d-alimentation-bouchon-de-reservoir-de-carburant',
    'circuit-d-alimentation-jauge-a-carburant',
    'circuit-d-alimentation-capteur-pression-de-carburant',
    'circuit-d-alimentation-capteur-temperature-carburant',
    'circuit-d-alimentation-joint-injecteur',
    'circuit-d-alimentation-joint-de-pompe-a-carburant',
    'circuit-d-alimentation-joint-de-pompe-a-injection',
    'circuit-d-alimentation-joint-d-etancheite-tuyauterie-de-carburant',
    'circuit-d-alimentation-joint-d-etancheite-filtre-de-carburant',
    'circuit-d-alimentation-soupape-de-filtre-a-carburant',
    'circuit-d-alimentation-filtre-unite-d-alimentation-de-carburant',
    'circuit-d-alimentation-pompe-de-gavage',
    'circuit-d-alimentation-relais-de-pompe-de-gavage',
    'circuit-d-alimentation-accumulateur-de-pression-de-carburant',
    'circuit-d-alimentation-electrovanne-de-pompe-d-injection',
    'circuit-d-alimentation-systeme-d-injection',
    'circuit-d-alimentation-kit-d-assemblage-pompe-a-carburant',
    'circuit-d-alimentation-tuyau-carburant-de-fuite',
    'circuit-d-alimentation-tuyau-de-ventilation-reservoir-de-carburant',
    'circuit-d-alimentation-soupape-de-ventilation-de-reservoir-de-carburant',
    'circuit-d-alimentation-palpeur-de-niveau-circuit-de-carburant',
    'circuit-d-alimentation-joint-d-etancheite-palpeur-de-reservoir',
    'circuit-d-alimentation-capteur-de-pression-reservoir-de-carburant',
    'circuit-d-alimentation-composants-du-carburateur',
    'circuit-d-alimentation-semelle-de-carburateur',
    'circuit-d-alimentation-kit-de-reparation-carburateur',
    'circuit-d-alimentation-kit-de-reparation-injecteur'
  ]) as slug,
  'local_gas_station' as icon,
  c.id as parent_id,
  generate_series(1, 35) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'circuit-d-alimentation' AND c.parent_id IS NULL;

-- =============================================
-- 16. ADMISSION ET TURBO (23 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Turbo',
    'Intercooler',
    'Débitmètre d''air',
    'Boîtier papillon',
    'Durite de turbo',
    'Durite d''admission d''air',
    'Capteur de pression d''admission',
    'Capteur de pression de suralimentation',
    'Régulateur de ralenti',
    'Capteur température d''air admission',
    'Câble d''accélérateur',
    'Capteur de position du papillon',
    'Valve d''air de circulation compresseur',
    'Capteur de position de pédale d''accélérateur',
    'Bague d''étanchéité, gaine de suralimentation',
    'Joint de turbo',
    'Kit montage compresseur',
    'Électrovanne de turbo',
    'Tuyau de graissage turbo',
    'Actuateur de ralenti',
    'Élément d''ajustage, papillon des gaz',
    'Pédale d''accélérateur',
    'Support bloc du filtre a air'
  ]) as name,
  unnest(ARRAY[
    'admission-et-turbo-turbo',
    'admission-et-turbo-intercooler',
    'admission-et-turbo-debitmetre-d-air',
    'admission-et-turbo-boitier-papillon',
    'admission-et-turbo-durite-de-turbo',
    'admission-et-turbo-durite-d-admission-d-air',
    'admission-et-turbo-capteur-de-pression-d-admission',
    'admission-et-turbo-capteur-de-pression-de-suralimentation',
    'admission-et-turbo-regulateur-de-ralenti',
    'admission-et-turbo-capteur-temperature-d-air-admission',
    'admission-et-turbo-cable-d-accelerateur',
    'admission-et-turbo-capteur-de-position-du-papillon',
    'admission-et-turbo-valve-d-air-de-circulation-compresseur',
    'admission-et-turbo-capteur-de-position-de-pedale-d-accelerateur',
    'admission-et-turbo-bague-d-etancheite-gaine-de-suralimentation',
    'admission-et-turbo-joint-de-turbo',
    'admission-et-turbo-kit-montage-compresseur',
    'admission-et-turbo-electrovanne-de-turbo',
    'admission-et-turbo-tuyau-de-graissage-turbo',
    'admission-et-turbo-actuateur-de-ralenti',
    'admission-et-turbo-element-d-ajustage-papillon-des-gaz',
    'admission-et-turbo-pedale-d-accelerateur',
    'admission-et-turbo-support-bloc-du-filtre-a-air'
  ]) as slug,
  'speed' as icon,
  c.id as parent_id,
  generate_series(1, 23) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'admission-et-turbo' AND c.parent_id IS NULL;

-- =============================================
-- 17. DIRECTION (26 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Crémaillère de direction',
    'Pompe de direction assistée',
    'Rotule de direction',
    'Rotule axiale',
    'Barre de direction',
    'Biellette de direction',
    'Arbre de direction',
    'Soufflet de direction',
    'Durite de direction assistée',
    'Réservoir de liquide de direction assistée',
    'Filtre hydraulique de direction',
    'Huile direction assistée',
    'Poulie de pompe de direction assistée',
    'Jeu de joints d''étanchéité, pompe hydraulique',
    'Radiateur d''huile, direction',
    'Kit de réparation de crémaillère de direction',
    'Amortisseur de direction',
    'Cardan de colonne de direction',
    'Silent bloc de direction',
    'Capteur d''angle de braquage',
    'Colonne de direction + direction assistée électrique',
    'Indicateur de pression d''huile',
    'Pièces de transmission de direction',
    'Levier de direction',
    'Douille, arbre de levier de direction',
    'Kit de réparation, rotule de barre de connexion'
  ]) as name,
  unnest(ARRAY[
    'direction-cremaillere-de-direction',
    'direction-pompe-de-direction-assistee',
    'direction-rotule-de-direction',
    'direction-rotule-axiale',
    'direction-barre-de-direction',
    'direction-biellette-de-direction',
    'direction-arbre-de-direction',
    'direction-soufflet-de-direction',
    'direction-durite-de-direction-assistee',
    'direction-reservoir-de-liquide-de-direction-assistee',
    'direction-filtre-hydraulique-de-direction',
    'direction-huile-direction-assistee',
    'direction-poulie-de-pompe-de-direction-assistee',
    'direction-jeu-de-joints-d-etancheite-pompe-hydraulique',
    'direction-radiateur-d-huile-direction',
    'direction-kit-de-reparation-de-cremaillere-de-direction',
    'direction-amortisseur-de-direction',
    'direction-cardan-de-colonne-de-direction',
    'direction-silent-bloc-de-direction',
    'direction-capteur-d-angle-de-braquage',
    'direction-colonne-de-direction-direction-assistee-electrique',
    'direction-indicateur-de-pression-d-huile',
    'direction-pieces-de-transmission-de-direction',
    'direction-levier-de-direction',
    'direction-douille-arbre-de-levier-de-direction',
    'direction-kit-de-reparation-rotule-de-barre-de-connexion'
  ]) as slug,
  'swap_horizontal_circle' as icon,
  c.id as parent_id,
  generate_series(1, 26) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'direction' AND c.parent_id IS NULL;

-- =============================================
-- 18. EMBRAYAGE (21 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Kit d''embrayage',
    'Disque d''embrayage',
    'Mécanisme d''embrayage',
    'Butée d''embrayage',
    'Butée d''embrayage hydraulique',
    'Émetteur d''embrayage',
    'Récepteur d''embrayage',
    'Câble d''embrayage',
    'Volant moteur',
    'Fourchette d''embrayage',
    'Guide de butée d''embrayage',
    'Palier guide / rondelle de butée',
    'Kit d''assemblage, cylindre émetteur d''embrayage',
    'Kit d''assemblage, cylindre récepteur d''embrayage',
    'Capteur d''embrayage',
    'Tuyau d''embrayage',
    'Butée, commande d''embrayage',
    'Embrayage renforcé',
    'Vis de volant moteur',
    'Cylindre émetteur',
    'Butée d''embrayage / débrayage central'
  ]) as name,
  unnest(ARRAY[
    'embrayage-kit-d-embrayage',
    'embrayage-disque-d-embrayage',
    'embrayage-mecanisme-d-embrayage',
    'embrayage-butee-d-embrayage',
    'embrayage-butee-d-embrayage-hydraulique',
    'embrayage-emetteur-d-embrayage',
    'embrayage-recepteur-d-embrayage',
    'embrayage-cable-d-embrayage',
    'embrayage-volant-moteur',
    'embrayage-fourchette-d-embrayage',
    'embrayage-guide-de-butee-d-embrayage',
    'embrayage-palier-guide-rondelle-de-butee',
    'embrayage-kit-d-assemblage-cylindre-emetteur-d-embrayage',
    'embrayage-kit-d-assemblage-cylindre-recepteur-d-embrayage',
    'embrayage-capteur-d-embrayage',
    'embrayage-tuyau-d-embrayage',
    'embrayage-butee-commande-d-embrayage',
    'embrayage-embrayage-renforce',
    'embrayage-vis-de-volant-moteur',
    'embrayage-cylindre-emetteur',
    'embrayage-butee-d-embrayage-debrayage-central'
  ]) as slug,
  'settings_backup_restore' as icon,
  c.id as parent_id,
  generate_series(1, 21) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'embrayage' AND c.parent_id IS NULL;

-- =============================================
-- 19. TRANSMISSION (38 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Cardan',
    'Arbre de transmission',
    'Soufflet de cardan',
    'Tripode',
    'Joint homocinétique',
    'Vis de cardan',
    'Huile boîte de vitesse',
    'Huile pour boîte de vitesse automatique',
    'Filtre boite automatique',
    'Kit pour vidange de boite automatique',
    'Carter de boîte de vitesse automatique',
    'Joint carte d''huile boite à vitesses automatique',
    'Radiateur d''huile de boite de vitesse automatique',
    'Pommeau de levier de vitesse',
    'Tringlerie de boîte de vitesse',
    'Kit de réparation, levier de changement de vitesse',
    'Support de boite de vitesse',
    'Silent bloc de boîte de transfert',
    'Contacteur de feu de recul',
    'Capteur de vitesse',
    'Calculateur boîte de vitesse automatique',
    'Valve de commande, boîte automatique',
    'Kit de réparation boîte de vitesse',
    'Suspension boîte manuelle',
    'Kit de réparation, flasque de boîte de vitesse manuelle',
    'Composants boite de vitesse',
    'Couvercle de flasque, boîte de vitesse manuelle',
    'Palier d''arbre de transmission',
    'Douille de centrage d''arbre longitudinal',
    'Bague d''étanchéité, arbre de transmission',
    'Bague d''étanchéité, arbre intermédiaire',
    'Bague d''étanchéité, casier de transfert',
    'Bague d''étanchéité de différentiel',
    'Joint spi de boîte de vitesse manuel',
    'Composantes différentielle',
    'Kit de réparation, différentiel',
    'Flector de transmission',
    'Kit de réparation, ajustage automatique'
  ]) as name,
  unnest(ARRAY[
    'transmission-cardan',
    'transmission-arbre-de-transmission',
    'transmission-soufflet-de-cardan',
    'transmission-tripode',
    'transmission-joint-homocinetique',
    'transmission-vis-de-cardan',
    'transmission-huile-boite-de-vitesse',
    'transmission-huile-pour-boite-de-vitesse-automatique',
    'transmission-filtre-boite-automatique',
    'transmission-kit-pour-vidange-de-boite-automatique',
    'transmission-carter-de-boite-de-vitesse-automatique',
    'transmission-joint-carte-d-huile-boite-a-vitesses-automatique',
    'transmission-radiateur-d-huile-de-boite-de-vitesse-automatique',
    'transmission-pommeau-de-levier-de-vitesse',
    'transmission-tringlerie-de-boite-de-vitesse',
    'transmission-kit-de-reparation-levier-de-changement-de-vitesse',
    'transmission-support-de-boite-de-vitesse',
    'transmission-silent-bloc-de-boite-de-transfert',
    'transmission-contacteur-de-feu-de-recul',
    'transmission-capteur-de-vitesse',
    'transmission-calculateur-boite-de-vitesse-automatique',
    'transmission-valve-de-commande-boite-automatique',
    'transmission-kit-de-reparation-boite-de-vitesse',
    'transmission-suspension-boite-manuelle',
    'transmission-kit-de-reparation-flasque-de-boite-de-vitesse-manuelle',
    'transmission-composants-boite-de-vitesse',
    'transmission-couvercle-de-flasque-boite-de-vitesse-manuelle',
    'transmission-palier-d-arbre-de-transmission',
    'transmission-douille-de-centrage-d-arbre-longitudinal',
    'transmission-bague-d-etancheite-arbre-de-transmission',
    'transmission-bague-d-etancheite-arbre-intermediaire',
    'transmission-bague-d-etancheite-casier-de-transfert',
    'transmission-bague-d-etancheite-de-differentiel',
    'transmission-joint-spi-de-boite-de-vitesse-manuel',
    'transmission-composantes-differentielle',
    'transmission-kit-de-reparation-differentiel',
    'transmission-flector-de-transmission',
    'transmission-kit-de-reparation-ajustage-automatique'
  ]) as slug,
  'settings_input_component' as icon,
  c.id as parent_id,
  generate_series(1, 38) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'transmission' AND c.parent_id IS NULL;

-- =============================================
-- 20. CLIMATISATION ET CHAUFFAGE (41 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Compresseur de climatisation',
    'Condenseur de clim',
    'Radiateur de chauffage',
    'Évaporateur de clim',
    'Filtre d''habitacle',
    'Bouteille déshydratante',
    'Détendeur de climatisation',
    'Embrayage de compresseur de clim',
    'Ventilateur d''habitacle',
    'Résistance de chauffage',
    'Poulie de compresseur de clim',
    'Gaz climatisation',
    'Huile de climatisation',
    'Capteur de pression de climatisation',
    'Contacteur de pression de clim',
    'Pressostat de climatisation',
    'Relais de clim',
    'Flexible de climatisation',
    'Durite de climatisation',
    'Joint de climatisation',
    'Tuyau haute pression de climatisation',
    'Tuyau basse pression de climatisation',
    'Pulseur d''air d''habitacle',
    'Moto-ventilateur d''habitacle',
    'Résistance moto-ventilateur',
    'Commande de chauffage',
    'Commande de climatisation',
    'Volet de régulation',
    'Actionneur de volet de chauffage',
    'Sonde de température intérieure',
    'Sonde de température extérieure',
    'Capteur ensoleillement',
    'Échangeur de chauffage',
    'Kit de recharge climatisation',
    'Nettoyant climatisation',
    'Joint collerette de climatisation',
    'Joint d''étanchéité conduit de climatisation',
    'Joint d''étanchéité tuyau de réfrigérant',
    'Kit de montage compresseur de clim',
    'Chauffage auxiliaire',
    'Pompe de chauffage supplémentaire'
  ]) as name,
  unnest(ARRAY[
    'climatisation-et-chauffage-compresseur-de-climatisation',
    'climatisation-et-chauffage-condenseur-de-clim',
    'climatisation-et-chauffage-radiateur-de-chauffage',
    'climatisation-et-chauffage-evaporateur-de-clim',
    'climatisation-et-chauffage-filtre-d-habitacle',
    'climatisation-et-chauffage-bouteille-deshydratante',
    'climatisation-et-chauffage-detendeur-de-climatisation',
    'climatisation-et-chauffage-embrayage-de-compresseur-de-clim',
    'climatisation-et-chauffage-ventilateur-d-habitacle',
    'climatisation-et-chauffage-resistance-de-chauffage',
    'climatisation-et-chauffage-poulie-de-compresseur-de-clim',
    'climatisation-et-chauffage-gaz-climatisation',
    'climatisation-et-chauffage-huile-de-climatisation',
    'climatisation-et-chauffage-capteur-de-pression-de-climatisation',
    'climatisation-et-chauffage-contacteur-de-pression-de-clim',
    'climatisation-et-chauffage-pressostat-de-climatisation',
    'climatisation-et-chauffage-relais-de-clim',
    'climatisation-et-chauffage-flexible-de-climatisation',
    'climatisation-et-chauffage-durite-de-climatisation',
    'climatisation-et-chauffage-joint-de-climatisation',
    'climatisation-et-chauffage-tuyau-haute-pression-de-climatisation',
    'climatisation-et-chauffage-tuyau-basse-pression-de-climatisation',
    'climatisation-et-chauffage-pulseur-d-air-d-habitacle',
    'climatisation-et-chauffage-moto-ventilateur-d-habitacle',
    'climatisation-et-chauffage-resistance-moto-ventilateur',
    'climatisation-et-chauffage-commande-de-chauffage',
    'climatisation-et-chauffage-commande-de-climatisation',
    'climatisation-et-chauffage-volet-de-regulation',
    'climatisation-et-chauffage-actionneur-de-volet-de-chauffage',
    'climatisation-et-chauffage-sonde-de-temperature-interieure',
    'climatisation-et-chauffage-sonde-de-temperature-exterieure',
    'climatisation-et-chauffage-capteur-ensoleillement',
    'climatisation-et-chauffage-echangeur-de-chauffage',
    'climatisation-et-chauffage-kit-de-recharge-climatisation',
    'climatisation-et-chauffage-nettoyant-climatisation',
    'climatisation-et-chauffage-joint-collerette-de-climatisation',
    'climatisation-et-chauffage-joint-d-etancheite-conduit-de-climatisation',
    'climatisation-et-chauffage-joint-d-etancheite-tuyau-de-refrigerant',
    'climatisation-et-chauffage-kit-de-montage-compresseur-de-clim',
    'climatisation-et-chauffage-chauffage-auxiliaire',
    'climatisation-et-chauffage-pompe-de-chauffage-supplementaire'
  ]) as slug,
  'ac_unit' as icon,
  c.id as parent_id,
  generate_series(1, 41) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'climatisation-et-chauffage' AND c.parent_id IS NULL;

-- =============================================
-- 21. ROUE ET PNEU (20 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Pneu été',
    'Pneu hiver',
    'Pneu 4 saisons',
    'Jante acier',
    'Jante alu',
    'Enjoliveur',
    'Cache moyeu',
    'Boulon de roue',
    'Écrou de roue',
    'Antivol de roue',
    'Valve de pneu',
    'Kit de réparation de pneu',
    'Chaînes neige',
    'Chaussettes neige',
    'Bouchon de valve',
    'Capteur de pression de pneu',
    'Entretoise de roue',
    'Adaptateur de roue',
    'Joint de jante',
    'Kit de montage de roue'
  ]) as name,
  unnest(ARRAY[
    'roue-et-pneu-pneu-ete',
    'roue-et-pneu-pneu-hiver',
    'roue-et-pneu-pneu-4-saisons',
    'roue-et-pneu-jante-acier',
    'roue-et-pneu-jante-alu',
    'roue-et-pneu-enjoliveur',
    'roue-et-pneu-cache-moyeu',
    'roue-et-pneu-boulon-de-roue',
    'roue-et-pneu-ecrou-de-roue',
    'roue-et-pneu-antivol-de-roue',
    'roue-et-pneu-valve-de-pneu',
    'roue-et-pneu-kit-de-reparation-de-pneu',
    'roue-et-pneu-chaines-neige',
    'roue-et-pneu-chaussettes-neige',
    'roue-et-pneu-bouchon-de-valve',
    'roue-et-pneu-capteur-de-pression-de-pneu',
    'roue-et-pneu-entretoise-de-roue',
    'roue-et-pneu-adaptateur-de-roue',
    'roue-et-pneu-joint-de-jante',
    'roue-et-pneu-kit-de-montage-de-roue'
  ]) as slug,
  'album' as icon,
  c.id as parent_id,
  generate_series(1, 20) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'roue-et-pneu' AND c.parent_id IS NULL;

-- =============================================
-- 22. INTÉRIEUR (45 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Tapis de sol',
    'Housse de siège',
    'Volant',
    'Pommeau de levier de vitesse',
    'Pédalier',
    'Pédale d''accélérateur',
    'Pédale de frein',
    'Pédale d''embrayage',
    'Accoudoir',
    'Vide-poche',
    'Boîte à gants',
    'Poignée boîte à gant',
    'Console centrale',
    'Habillage de porte',
    'Garniture de tableau de bord',
    'Ciel de toit',
    'Pare-soleil',
    'Miroir de courtoisie',
    'Cendrier',
    'Allume-cigare',
    'Prise 12V',
    'Grille de haut-parleur',
    'Cache airbag',
    'Siège',
    'Mécanisme de siège',
    'Commande de siège électrique',
    'Résistance de siège chauffant',
    'Relais de siège chauffant',
    'Garniture de siège',
    'Accoudoir central',
    'Repose-tête',
    'Appui-tête',
    'Ceinture de sécurité',
    'Enrouleur de ceinture',
    'Boucle de ceinture',
    'Prétensionneur de ceinture',
    'Cache de ceinture',
    'Airbag',
    'Airbag conducteur',
    'Airbag passager',
    'Airbag latéral',
    'Airbag rideau',
    'Calculateur airbag',
    'Contacteur tournant airbag',
    'Capteur de choc'
  ]) as name,
  unnest(ARRAY[
    'interieur-tapis-de-sol',
    'interieur-housse-de-siege',
    'interieur-volant',
    'interieur-pommeau-de-levier-de-vitesse',
    'interieur-pedalier',
    'interieur-pedale-d-accelerateur',
    'interieur-pedale-de-frein',
    'interieur-pedale-d-embrayage',
    'interieur-accoudoir',
    'interieur-vide-poche',
    'interieur-boite-a-gants',
    'interieur-poignee-boite-a-gant',
    'interieur-console-centrale',
    'interieur-habillage-de-porte',
    'interieur-garniture-de-tableau-de-bord',
    'interieur-ciel-de-toit',
    'interieur-pare-soleil',
    'interieur-miroir-de-courtoisie',
    'interieur-cendrier',
    'interieur-allume-cigare',
    'interieur-prise-12v',
    'interieur-grille-de-haut-parleur',
    'interieur-cache-airbag',
    'interieur-siege',
    'interieur-mecanisme-de-siege',
    'interieur-commande-de-siege-electrique',
    'interieur-resistance-de-siege-chauffant',
    'interieur-relais-de-siege-chauffant',
    'interieur-garniture-de-siege',
    'interieur-accoudoir-central',
    'interieur-repose-tete',
    'interieur-appui-tete',
    'interieur-ceinture-de-securite',
    'interieur-enrouleur-de-ceinture',
    'interieur-boucle-de-ceinture',
    'interieur-pretensionneur-de-ceinture',
    'interieur-cache-de-ceinture',
    'interieur-airbag',
    'interieur-airbag-conducteur',
    'interieur-airbag-passager',
    'interieur-airbag-lateral',
    'interieur-airbag-rideau',
    'interieur-calculateur-airbag',
    'interieur-contacteur-tournant-airbag',
    'interieur-capteur-de-choc'
  ]) as slug,
  'event_seat' as icon,
  c.id as parent_id,
  generate_series(1, 45) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'interieur' AND c.parent_id IS NULL;

-- =============================================
-- 23. ENTRETIEN (33 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Kit d''entretien',
    'Huile moteur',
    'Filtre à huile',
    'Filtre à air',
    'Filtre d''habitacle',
    'Filtre à carburant',
    'Bougies',
    'Balais d''essuie-glace',
    'Liquide de refroidissement',
    'Liquide de frein',
    'Lave-glace',
    'AdBlue',
    'Produit d''entretien',
    'Nettoyant moteur',
    'Nettoyant injecteur',
    'Nettoyant FAP',
    'Nettoyant climatisation',
    'Dégrippant',
    'Graisse',
    'Pâte à joint',
    'Mastic',
    'Silicone',
    'Polish',
    'Cire de protection',
    'Shampoing auto',
    'Nettoyant jantes',
    'Nettoyant plastique',
    'Rénovateur plastique',
    'Traitement cuir',
    'Désodorisant',
    'Microfibre',
    'Éponge',
    'Kit de vidange'
  ]) as name,
  unnest(ARRAY[
    'entretien-kit-d-entretien',
    'entretien-huile-moteur',
    'entretien-filtre-a-huile',
    'entretien-filtre-a-air',
    'entretien-filtre-d-habitacle',
    'entretien-filtre-a-carburant',
    'entretien-bougies',
    'entretien-balais-d-essuie-glace',
    'entretien-liquide-de-refroidissement',
    'entretien-liquide-de-frein',
    'entretien-lave-glace',
    'entretien-adblue',
    'entretien-produit-d-entretien',
    'entretien-nettoyant-moteur',
    'entretien-nettoyant-injecteur',
    'entretien-nettoyant-fap',
    'entretien-nettoyant-climatisation',
    'entretien-degrippant',
    'entretien-graisse',
    'entretien-pate-a-joint',
    'entretien-mastic',
    'entretien-silicone',
    'entretien-polish',
    'entretien-cire-de-protection',
    'entretien-shampoing-auto',
    'entretien-nettoyant-jantes',
    'entretien-nettoyant-plastique',
    'entretien-renovateur-plastique',
    'entretien-traitement-cuir',
    'entretien-desodorisant',
    'entretien-microfibre',
    'entretien-eponge',
    'entretien-kit-de-vidange'
  ]) as slug,
  'build_circle' as icon,
  c.id as parent_id,
  generate_series(1, 33) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'entretien' AND c.parent_id IS NULL;

-- =============================================
-- 24. OUTILLAGE (39 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Clé dynamométrique',
    'Clé à molette',
    'Jeu de clés',
    'Jeu de douilles',
    'Tournevis',
    'Pince',
    'Marteau',
    'Extracteur',
    'Compresseur de ressort',
    'Arrache rotule',
    'Clé de filtre à huile',
    'Clé de filtre à carburant',
    'Coffret d''outils',
    'Cric',
    'Chandelle',
    'Rampe de levage',
    'Pont élévateur',
    'Chariot de visite',
    'Bac de vidange',
    'Pompe de vidange',
    'Entonnoir',
    'Jerrican',
    'Pistolet à graisse',
    'Manomètre',
    'Multimètre',
    'Valise diagnostic',
    'Appareil de diagnostic',
    'Lampe d''atelier',
    'Lampe de poche',
    'Brosse métallique',
    'Grattoir',
    'Clé de purge de frein',
    'Kit de purge de frein',
    'Compresseur d''air',
    'Soufflette',
    'Pistolet de gonflage',
    'Démonte-pneu',
    'Équilibreuse',
    'Marbre de contrôle'
  ]) as name,
  unnest(ARRAY[
    'outillage-cle-dynamometrique',
    'outillage-cle-a-molette',
    'outillage-jeu-de-cles',
    'outillage-jeu-de-douilles',
    'outillage-tournevis',
    'outillage-pince',
    'outillage-marteau',
    'outillage-extracteur',
    'outillage-compresseur-de-ressort',
    'outillage-arrache-rotule',
    'outillage-cle-de-filtre-a-huile',
    'outillage-cle-de-filtre-a-carburant',
    'outillage-coffret-d-outils',
    'outillage-cric',
    'outillage-chandelle',
    'outillage-rampe-de-levage',
    'outillage-pont-elevateur',
    'outillage-chariot-de-visite',
    'outillage-bac-de-vidange',
    'outillage-pompe-de-vidange',
    'outillage-entonnoir',
    'outillage-jerrican',
    'outillage-pistolet-a-graisse',
    'outillage-manometre',
    'outillage-multimetre',
    'outillage-valise-diagnostic',
    'outillage-appareil-de-diagnostic',
    'outillage-lampe-d-atelier',
    'outillage-lampe-de-poche',
    'outillage-brosse-metallique',
    'outillage-grattoir',
    'outillage-cle-de-purge-de-frein',
    'outillage-kit-de-purge-de-frein',
    'outillage-compresseur-d-air',
    'outillage-soufflette',
    'outillage-pistolet-de-gonflage',
    'outillage-demonte-pneu',
    'outillage-equilibreuse',
    'outillage-marbre-de-controle'
  ]) as slug,
  'construction' as icon,
  c.id as parent_id,
  generate_series(1, 39) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'outillage' AND c.parent_id IS NULL;

-- =============================================
-- 25. ÉQUIPEMENT AUTO (50 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Attelage',
    'Porte-vélo',
    'Coffre de toit',
    'Barre de toit',
    'Porte-skis',
    'Galerie',
    'Marchepied',
    'Pare-buffle',
    'Déflecteur de capot',
    'Déflecteur de porte',
    'Bavette',
    'Pare-boue',
    'Crochet de remorquage',
    'Sangle de remorquage',
    'Câble de remorquage',
    'Triangle de signalisation',
    'Gilet de sécurité',
    'Trousse de secours',
    'Extincteur',
    'Éthylotest',
    'Disque de stationnement',
    'Support de smartphone',
    'Chargeur de téléphone',
    'Dashcam',
    'Caméra de recul',
    'Radar de recul',
    'GPS',
    'Autoradio',
    'Kit main libre',
    'Amplificateur',
    'Haut-parleur',
    'Caisson de basse',
    'Antenne',
    'Siège auto enfant',
    'Rehausseur',
    'Organiseur de coffre',
    'Filet de coffre',
    'Bâche de protection',
    'Housse de voiture',
    'Pare-soleil',
    'Rideau',
    'Grattoir à glace',
    'Balai de neige',
    'Dégivreur',
    'Housse de volant',
    'Coussin de siège',
    'Coussin chauffant',
    'Ventilateur 12V',
    'Glacière 12V',
    'Aspirateur 12V'
  ]) as name,
  unnest(ARRAY[
    'equipement-auto-attelage',
    'equipement-auto-porte-velo',
    'equipement-auto-coffre-de-toit',
    'equipement-auto-barre-de-toit',
    'equipement-auto-porte-skis',
    'equipement-auto-galerie',
    'equipement-auto-marchepied',
    'equipement-auto-pare-buffle',
    'equipement-auto-deflecteur-de-capot',
    'equipement-auto-deflecteur-de-porte',
    'equipement-auto-bavette',
    'equipement-auto-pare-boue',
    'equipement-auto-crochet-de-remorquage',
    'equipement-auto-sangle-de-remorquage',
    'equipement-auto-cable-de-remorquage',
    'equipement-auto-triangle-de-signalisation',
    'equipement-auto-gilet-de-securite',
    'equipement-auto-trousse-de-secours',
    'equipement-auto-extincteur',
    'equipement-auto-ethylotest',
    'equipement-auto-disque-de-stationnement',
    'equipement-auto-support-de-smartphone',
    'equipement-auto-chargeur-de-telephone',
    'equipement-auto-dashcam',
    'equipement-auto-camera-de-recul',
    'equipement-auto-radar-de-recul',
    'equipement-auto-gps',
    'equipement-auto-autoradio',
    'equipement-auto-kit-main-libre',
    'equipement-auto-amplificateur',
    'equipement-auto-haut-parleur',
    'equipement-auto-caisson-de-basse',
    'equipement-auto-antenne',
    'equipement-auto-siege-auto-enfant',
    'equipement-auto-rehausseur',
    'equipement-auto-organiseur-de-coffre',
    'equipement-auto-filet-de-coffre',
    'equipement-auto-bache-de-protection',
    'equipement-auto-housse-de-voiture',
    'equipement-auto-pare-soleil',
    'equipement-auto-rideau',
    'equipement-auto-grattoir-a-glace',
    'equipement-auto-balai-de-neige',
    'equipement-auto-degivreur',
    'equipement-auto-housse-de-volant',
    'equipement-auto-coussin-de-siege',
    'equipement-auto-coussin-chauffant',
    'equipement-auto-ventilateur-12v',
    'equipement-auto-glaciere-12v',
    'equipement-auto-aspirateur-12v'
  ]) as slug,
  'drive_eta' as icon,
  c.id as parent_id,
  generate_series(1, 50) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'equipement-auto' AND c.parent_id IS NULL;

-- =============================================
-- 26. TUNING ET PERFORMANCE (76 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Kit carrosserie',
    'Becquet',
    'Spoiler',
    'Diffuseur',
    'Lame de pare-choc',
    'Bas de caisse',
    'Élargisseur d''aile',
    'Calandre sport',
    'Grille de calandre',
    'Capot',
    'Capot carbone',
    'Aile avant',
    'Échappement sport',
    'Embout d''échappement',
    'Silencieux sport',
    'Catalyseur sport',
    'Downpipe',
    'Décatalyseur',
    'Filtre à air sport',
    'Kit admission directe',
    'Admission dynamique',
    'Boîtier additionnel',
    'Reprogrammation moteur',
    'Dump valve',
    'Wastegate',
    'Intercooler sport',
    'Radiateur d''huile sport',
    'Radiateur d''eau sport',
    'Kit de suralimentation',
    'Turbo préparé',
    'Embrayage renforcé',
    'Volant moteur allégé',
    'Kit de distribution renforcé',
    'Poulie damper',
    'Courroie d''accessoire renforcée',
    'Support moteur rigide',
    'Barre anti-rapprochement',
    'Triangulation',
    'Barre de renfort',
    'Suspension sport',
    'Ressort court',
    'Amortisseur sport',
    'Kit combinés filetés',
    'Barre stabilisatrice sport',
    'Silent bloc polyuréthane',
    'Kit de freinage sport',
    'Disque de frein sport',
    'Plaquette de frein sport',
    'Durite aviation',
    'Maître-cylindre sport',
    'Étrier de frein sport',
    'Kit big brake',
    'Liquide de frein sport',
    'Jante alu sport',
    'Pneu sport',
    'Entretoises de roue',
    'Écrou de roue sport',
    'Antivol de roue sport',
    'Pommeau de vitesse sport',
    'Volant sport',
    'Pédalier sport',
    'Harnais de sécurité',
    'Arceau de sécurité',
    'Siège baquet',
    'Manomètre',
    'Compte-tours',
    'Boost controller',
    'Afficheur multifonction',
    'Bande autocollante',
    'Sticker',
    'Covering',
    'Film teinté',
    'LED d''ambiance',
    'Néon de caisse',
    'Phare xénon',
    'Kit LED'
  ]) as name,
  unnest(ARRAY[
    'tuning-et-performance-kit-carrosserie',
    'tuning-et-performance-becquet',
    'tuning-et-performance-spoiler',
    'tuning-et-performance-diffuseur',
    'tuning-et-performance-lame-de-pare-choc',
    'tuning-et-performance-bas-de-caisse',
    'tuning-et-performance-elargisseur-d-aile',
    'tuning-et-performance-calandre-sport',
    'tuning-et-performance-grille-de-calandre',
    'tuning-et-performance-capot',
    'tuning-et-performance-capot-carbone',
    'tuning-et-performance-aile-avant',
    'tuning-et-performance-echappement-sport',
    'tuning-et-performance-embout-d-echappement',
    'tuning-et-performance-silencieux-sport',
    'tuning-et-performance-catalyseur-sport',
    'tuning-et-performance-downpipe',
    'tuning-et-performance-decatalyseur',
    'tuning-et-performance-filtre-a-air-sport',
    'tuning-et-performance-kit-admission-directe',
    'tuning-et-performance-admission-dynamique',
    'tuning-et-performance-boitier-additionnel',
    'tuning-et-performance-reprogrammation-moteur',
    'tuning-et-performance-dump-valve',
    'tuning-et-performance-wastegate',
    'tuning-et-performance-intercooler-sport',
    'tuning-et-performance-radiateur-d-huile-sport',
    'tuning-et-performance-radiateur-d-eau-sport',
    'tuning-et-performance-kit-de-suralimentation',
    'tuning-et-performance-turbo-prepare',
    'tuning-et-performance-embrayage-renforce',
    'tuning-et-performance-volant-moteur-allege',
    'tuning-et-performance-kit-de-distribution-renforce',
    'tuning-et-performance-poulie-damper',
    'tuning-et-performance-courroie-d-accessoire-renforcee',
    'tuning-et-performance-support-moteur-rigide',
    'tuning-et-performance-barre-anti-rapprochement',
    'tuning-et-performance-triangulation',
    'tuning-et-performance-barre-de-renfort',
    'tuning-et-performance-suspension-sport',
    'tuning-et-performance-ressort-court',
    'tuning-et-performance-amortisseur-sport',
    'tuning-et-performance-kit-combines-filetes',
    'tuning-et-performance-barre-stabilisatrice-sport',
    'tuning-et-performance-silent-bloc-polyurethane',
    'tuning-et-performance-kit-de-freinage-sport',
    'tuning-et-performance-disque-de-frein-sport',
    'tuning-et-performance-plaquette-de-frein-sport',
    'tuning-et-performance-durite-aviation',
    'tuning-et-performance-maitre-cylindre-sport',
    'tuning-et-performance-etrier-de-frein-sport',
    'tuning-et-performance-kit-big-brake',
    'tuning-et-performance-liquide-de-frein-sport',
    'tuning-et-performance-jante-alu-sport',
    'tuning-et-performance-pneu-sport',
    'tuning-et-performance-entretoises-de-roue',
    'tuning-et-performance-ecrou-de-roue-sport',
    'tuning-et-performance-antivol-de-roue-sport',
    'tuning-et-performance-pommeau-de-vitesse-sport',
    'tuning-et-performance-volant-sport',
    'tuning-et-performance-pedalier-sport',
    'tuning-et-performance-harnais-de-securite',
    'tuning-et-performance-arceau-de-securite',
    'tuning-et-performance-siege-baquet',
    'tuning-et-performance-manometre',
    'tuning-et-performance-compte-tours',
    'tuning-et-performance-boost-controller',
    'tuning-et-performance-afficheur-multifonction',
    'tuning-et-performance-bande-autocollante',
    'tuning-et-performance-sticker',
    'tuning-et-performance-covering',
    'tuning-et-performance-film-teinte',
    'tuning-et-performance-led-d-ambiance',
    'tuning-et-performance-neon-de-caisse',
    'tuning-et-performance-phare-xenon',
    'tuning-et-performance-kit-led'
  ]) as slug,
  'speed' as icon,
  c.id as parent_id,
  generate_series(1, 76) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'tuning-et-performance' AND c.parent_id IS NULL;

-- =============================================
-- 27. PIÈCES UNIVERSELLES (34 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Joint universel',
    'Collier de serrage',
    'Vis',
    'Écrou',
    'Boulon',
    'Rondelle',
    'Goupille',
    'Rivet',
    'Clip',
    'Agrafe',
    'Câble',
    'Gaine',
    'Borne électrique',
    'Cosse électrique',
    'Connecteur électrique',
    'Domino électrique',
    'Fusible universel',
    'Relais universel',
    'Interrupteur',
    'Bouton poussoir',
    'Durite universelle',
    'Raccord universel',
    'Collier de durite',
    'Joint torique',
    'Joint plat',
    'Joint en caoutchouc',
    'Mousse d''étanchéité',
    'Ruban adhésif',
    'Scotch double face',
    'Chatterton',
    'Gaine thermorétractable',
    'Serre-câbles',
    'Fil électrique',
    'Câble de batterie'
  ]) as name,
  unnest(ARRAY[
    'pieces-universelles-joint-universel',
    'pieces-universelles-collier-de-serrage',
    'pieces-universelles-vis',
    'pieces-universelles-ecrou',
    'pieces-universelles-boulon',
    'pieces-universelles-rondelle',
    'pieces-universelles-goupille',
    'pieces-universelles-rivet',
    'pieces-universelles-clip',
    'pieces-universelles-agrafe',
    'pieces-universelles-cable',
    'pieces-universelles-gaine',
    'pieces-universelles-borne-electrique',
    'pieces-universelles-cosse-electrique',
    'pieces-universelles-connecteur-electrique',
    'pieces-universelles-domino-electrique',
    'pieces-universelles-fusible-universel',
    'pieces-universelles-relais-universel',
    'pieces-universelles-interrupteur',
    'pieces-universelles-bouton-poussoir',
    'pieces-universelles-durite-universelle',
    'pieces-universelles-raccord-universel',
    'pieces-universelles-collier-de-durite',
    'pieces-universelles-joint-torique',
    'pieces-universelles-joint-plat',
    'pieces-universelles-joint-en-caoutchouc',
    'pieces-universelles-mousse-d-etancheite',
    'pieces-universelles-ruban-adhesif',
    'pieces-universelles-scotch-double-face',
    'pieces-universelles-chatterton',
    'pieces-universelles-gaine-thermoretractable',
    'pieces-universelles-serre-cables',
    'pieces-universelles-fil-electrique',
    'pieces-universelles-cable-de-batterie'
  ]) as slug,
  'category' as icon,
  c.id as parent_id,
  generate_series(1, 34) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'pieces-universelles' AND c.parent_id IS NULL;

-- =============================================
-- 28. VÉHICULE UTILITAIRE (37 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Embrayage utilitaire',
    'Frein utilitaire',
    'Suspension utilitaire',
    'Amortisseur utilitaire',
    'Distribution utilitaire',
    'Filtre utilitaire',
    'Batterie utilitaire',
    'Alternateur utilitaire',
    'Démarreur utilitaire',
    'Turbo utilitaire',
    'Injecteur utilitaire',
    'Pompe à injection utilitaire',
    'Radiateur utilitaire',
    'Intercooler utilitaire',
    'Échappement utilitaire',
    'FAP utilitaire',
    'Catalyseur utilitaire',
    'Cardan utilitaire',
    'Crémaillère utilitaire',
    'Pompe de direction utilitaire',
    'Compresseur de clim utilitaire',
    'Phare utilitaire',
    'Feu arrière utilitaire',
    'Rétroviseur utilitaire',
    'Pare-choc utilitaire',
    'Aile utilitaire',
    'Porte utilitaire',
    'Hayon utilitaire',
    'Plancher utilitaire',
    'Ridelle',
    'Benne',
    'Système de bâchage',
    'Éclairage de travail',
    'Gyrophare',
    'Avertisseur sonore',
    'Marche-pied utilitaire',
    'Protection de seuil'
  ]) as name,
  unnest(ARRAY[
    'vehicule-utilitaire-embrayage-utilitaire',
    'vehicule-utilitaire-frein-utilitaire',
    'vehicule-utilitaire-suspension-utilitaire',
    'vehicule-utilitaire-amortisseur-utilitaire',
    'vehicule-utilitaire-distribution-utilitaire',
    'vehicule-utilitaire-filtre-utilitaire',
    'vehicule-utilitaire-batterie-utilitaire',
    'vehicule-utilitaire-alternateur-utilitaire',
    'vehicule-utilitaire-demarreur-utilitaire',
    'vehicule-utilitaire-turbo-utilitaire',
    'vehicule-utilitaire-injecteur-utilitaire',
    'vehicule-utilitaire-pompe-a-injection-utilitaire',
    'vehicule-utilitaire-radiateur-utilitaire',
    'vehicule-utilitaire-intercooler-utilitaire',
    'vehicule-utilitaire-echappement-utilitaire',
    'vehicule-utilitaire-fap-utilitaire',
    'vehicule-utilitaire-catalyseur-utilitaire',
    'vehicule-utilitaire-cardan-utilitaire',
    'vehicule-utilitaire-cremaillere-utilitaire',
    'vehicule-utilitaire-pompe-de-direction-utilitaire',
    'vehicule-utilitaire-compresseur-de-clim-utilitaire',
    'vehicule-utilitaire-phare-utilitaire',
    'vehicule-utilitaire-feu-arriere-utilitaire',
    'vehicule-utilitaire-retroviseur-utilitaire',
    'vehicule-utilitaire-pare-choc-utilitaire',
    'vehicule-utilitaire-aile-utilitaire',
    'vehicule-utilitaire-porte-utilitaire',
    'vehicule-utilitaire-hayon-utilitaire',
    'vehicule-utilitaire-plancher-utilitaire',
    'vehicule-utilitaire-ridelle',
    'vehicule-utilitaire-benne',
    'vehicule-utilitaire-systeme-de-bachage',
    'vehicule-utilitaire-eclairage-de-travail',
    'vehicule-utilitaire-gyrophare',
    'vehicule-utilitaire-avertisseur-sonore',
    'vehicule-utilitaire-marche-pied-utilitaire',
    'vehicule-utilitaire-protection-de-seuil'
  ]) as slug,
  'local_shipping' as icon,
  c.id as parent_id,
  generate_series(1, 37) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'vehicule-utilitaire' AND c.parent_id IS NULL;

-- =============================================
-- 29. POIDS LOURD (78 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Embrayage poids lourd',
    'Frein poids lourd',
    'Compresseur d''air',
    'Valve de frein',
    'Cylindre de frein',
    'Étrier de frein PL',
    'Disque de frein PL',
    'Plaquette de frein PL',
    'Mâchoire de frein PL',
    'Flexible de frein PL',
    'Suspension pneumatique PL',
    'Coussin d''air',
    'Valve de suspension',
    'Amortisseur PL',
    'Lame de ressort PL',
    'Essieu PL',
    'Moyeu PL',
    'Roulement PL',
    'Cardan PL',
    'Arbre de transmission PL',
    'Boîte de vitesse PL',
    'Embrayage PL',
    'Distribution PL',
    'Courroie PL',
    'Tendeur PL',
    'Turbo PL',
    'Intercooler PL',
    'Radiateur PL',
    'Ventilateur PL',
    'Thermostat PL',
    'Pompe à eau PL',
    'Filtre à air PL',
    'Filtre à huile PL',
    'Filtre à carburant PL',
    'Filtre dessiccateur',
    'Injecteur PL',
    'Pompe à injection PL',
    'Pompe de gavage PL',
    'Réservoir PL',
    'Réservoir AdBlue',
    'Pompe AdBlue',
    'Injecteur AdBlue',
    'Capteur NOx',
    'Échappement PL',
    'Silencieux PL',
    'FAP PL',
    'Catalyseur SCR',
    'Batterie PL',
    'Alternateur PL',
    'Démarreur PL',
    'Bobine d''allumage PL',
    'Bougie PL',
    'Phare PL',
    'Feu de position PL',
    'Feu de gabarit',
    'Rampe LED',
    'Gyrophare PL',
    'Rétroviseur PL',
    'Caméra PL',
    'Cabine PL',
    'Pare-choc PL',
    'Pare-buffle PL',
    'Marchepied PL',
    'Calandre PL',
    'Déflecteur de toit',
    'Déflecteur latéral',
    'Bavette PL',
    'Tapis de sol PL',
    'Siège PL',
    'Suspension de siège',
    'Volant PL',
    'Tableau de bord PL',
    'Climatisation PL',
    'Chauffage auxiliaire PL',
    'Attelage PL',
    'Sellette d''attelage',
    'Crochet d''attelage',
    'Prise remorque'
  ]) as name,
  unnest(ARRAY[
    'poids-lourd-embrayage-poids-lourd',
    'poids-lourd-frein-poids-lourd',
    'poids-lourd-compresseur-d-air',
    'poids-lourd-valve-de-frein',
    'poids-lourd-cylindre-de-frein',
    'poids-lourd-etrier-de-frein-pl',
    'poids-lourd-disque-de-frein-pl',
    'poids-lourd-plaquette-de-frein-pl',
    'poids-lourd-machoire-de-frein-pl',
    'poids-lourd-flexible-de-frein-pl',
    'poids-lourd-suspension-pneumatique-pl',
    'poids-lourd-coussin-d-air',
    'poids-lourd-valve-de-suspension',
    'poids-lourd-amortisseur-pl',
    'poids-lourd-lame-de-ressort-pl',
    'poids-lourd-essieu-pl',
    'poids-lourd-moyeu-pl',
    'poids-lourd-roulement-pl',
    'poids-lourd-cardan-pl',
    'poids-lourd-arbre-de-transmission-pl',
    'poids-lourd-boite-de-vitesse-pl',
    'poids-lourd-embrayage-pl',
    'poids-lourd-distribution-pl',
    'poids-lourd-courroie-pl',
    'poids-lourd-tendeur-pl',
    'poids-lourd-turbo-pl',
    'poids-lourd-intercooler-pl',
    'poids-lourd-radiateur-pl',
    'poids-lourd-ventilateur-pl',
    'poids-lourd-thermostat-pl',
    'poids-lourd-pompe-a-eau-pl',
    'poids-lourd-filtre-a-air-pl',
    'poids-lourd-filtre-a-huile-pl',
    'poids-lourd-filtre-a-carburant-pl',
    'poids-lourd-filtre-dessiccateur',
    'poids-lourd-injecteur-pl',
    'poids-lourd-pompe-a-injection-pl',
    'poids-lourd-pompe-de-gavage-pl',
    'poids-lourd-reservoir-pl',
    'poids-lourd-reservoir-adblue',
    'poids-lourd-pompe-adblue',
    'poids-lourd-injecteur-adblue',
    'poids-lourd-capteur-nox',
    'poids-lourd-echappement-pl',
    'poids-lourd-silencieux-pl',
    'poids-lourd-fap-pl',
    'poids-lourd-catalyseur-scr',
    'poids-lourd-batterie-pl',
    'poids-lourd-alternateur-pl',
    'poids-lourd-demarreur-pl',
    'poids-lourd-bobine-d-allumage-pl',
    'poids-lourd-bougie-pl',
    'poids-lourd-phare-pl',
    'poids-lourd-feu-de-position-pl',
    'poids-lourd-feu-de-gabarit',
    'poids-lourd-rampe-led',
    'poids-lourd-gyrophare-pl',
    'poids-lourd-retroviseur-pl',
    'poids-lourd-camera-pl',
    'poids-lourd-cabine-pl',
    'poids-lourd-pare-choc-pl',
    'poids-lourd-pare-buffle-pl',
    'poids-lourd-marchepied-pl',
    'poids-lourd-calandre-pl',
    'poids-lourd-deflecteur-de-toit',
    'poids-lourd-deflecteur-lateral',
    'poids-lourd-bavette-pl',
    'poids-lourd-tapis-de-sol-pl',
    'poids-lourd-siege-pl',
    'poids-lourd-suspension-de-siege',
    'poids-lourd-volant-pl',
    'poids-lourd-tableau-de-bord-pl',
    'poids-lourd-climatisation-pl',
    'poids-lourd-chauffage-auxiliaire-pl',
    'poids-lourd-attelage-pl',
    'poids-lourd-sellette-d-attelage',
    'poids-lourd-crochet-d-attelage',
    'poids-lourd-prise-remorque'
  ]) as slug,
  'local_shipping' as icon,
  c.id as parent_id,
  generate_series(1, 78) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'poids-lourd' AND c.parent_id IS NULL;

-- =============================================
-- 30. MOTO ET SCOOTER (71 sous-catégories)
-- =============================================
INSERT INTO public.categories (name, slug, icon, parent_id, display_order, is_active)
SELECT 
  unnest(ARRAY[
    'Casque moto',
    'Gants moto',
    'Blouson moto',
    'Pantalon moto',
    'Bottes moto',
    'Protection moto',
    'Pneu moto',
    'Pneu scooter',
    'Chambre à air moto',
    'Batterie moto',
    'Bougie moto',
    'Filtre à huile moto',
    'Filtre à air moto',
    'Huile moteur moto',
    'Huile fourche moto',
    'Liquide de frein moto',
    'Chaîne de transmission moto',
    'Kit chaîne moto',
    'Couronne moto',
    'Pignon moto',
    'Plaquette de frein moto',
    'Disque de frein moto',
    'Plaquette de frein scooter',
    'Mâchoire de frein scooter',
    'Câble d''embrayage moto',
    'Câble de frein moto',
    'Câble d''accélérateur moto',
    'Levier d''embrayage moto',
    'Levier de frein moto',
    'Poignée moto',
    'Rétroviseur moto',
    'Clignotant moto',
    'Feu arrière moto',
    'Phare moto',
    'Ampoule moto',
    'Support de plaque moto',
    'Sacoches moto',
    'Top case',
    'Bulle moto',
    'Pare-brise moto',
    'Antivol moto',
    'Chaîne antivol',
    'Bloque disque',
    'Alarme moto',
    'Variateur scooter',
    'Embrayage scooter',
    'Courroie scooter',
    'Galet scooter',
    'Ressort de poussée scooter',
    'Cloche d''embrayage scooter',
    'Carburateur moto',
    'Pot d''échappement moto',
    'Silencieux moto',
    'Collecteur moto',
    'Kit piston moto',
    'Segment moto',
    'Cylindre moto',
    'Culasse moto',
    'Vilebrequin moto',
    'Arbre à came moto',
    'Soupape moto',
    'Ressort de soupape moto',
    'Joint de culasse moto',
    'Joint spy moto',
    'Fourche moto',
    'Amortisseur moto',
    'Bras oscillant moto',
    'Jante moto',
    'Moyeu moto',
    'Roulement de roue moto',
    'Étrier de frein moto'
  ]) as name,
  unnest(ARRAY[
    'moto-et-scooter-casque-moto',
    'moto-et-scooter-gants-moto',
    'moto-et-scooter-blouson-moto',
    'moto-et-scooter-pantalon-moto',
    'moto-et-scooter-bottes-moto',
    'moto-et-scooter-protection-moto',
    'moto-et-scooter-pneu-moto',
    'moto-et-scooter-pneu-scooter',
    'moto-et-scooter-chambre-a-air-moto',
    'moto-et-scooter-batterie-moto',
    'moto-et-scooter-bougie-moto',
    'moto-et-scooter-filtre-a-huile-moto',
    'moto-et-scooter-filtre-a-air-moto',
    'moto-et-scooter-huile-moteur-moto',
    'moto-et-scooter-huile-fourche-moto',
    'moto-et-scooter-liquide-de-frein-moto',
    'moto-et-scooter-chaine-de-transmission-moto',
    'moto-et-scooter-kit-chaine-moto',
    'moto-et-scooter-couronne-moto',
    'moto-et-scooter-pignon-moto',
    'moto-et-scooter-plaquette-de-frein-moto',
    'moto-et-scooter-disque-de-frein-moto',
    'moto-et-scooter-plaquette-de-frein-scooter',
    'moto-et-scooter-machoire-de-frein-scooter',
    'moto-et-scooter-cable-d-embrayage-moto',
    'moto-et-scooter-cable-de-frein-moto',
    'moto-et-scooter-cable-d-accelerateur-moto',
    'moto-et-scooter-levier-d-embrayage-moto',
    'moto-et-scooter-levier-de-frein-moto',
    'moto-et-scooter-poignee-moto',
    'moto-et-scooter-retroviseur-moto',
    'moto-et-scooter-clignotant-moto',
    'moto-et-scooter-feu-arriere-moto',
    'moto-et-scooter-phare-moto',
    'moto-et-scooter-ampoule-moto',
    'moto-et-scooter-support-de-plaque-moto',
    'moto-et-scooter-sacoches-moto',
    'moto-et-scooter-top-case',
    'moto-et-scooter-bulle-moto',
    'moto-et-scooter-pare-brise-moto',
    'moto-et-scooter-antivol-moto',
    'moto-et-scooter-chaine-antivol',
    'moto-et-scooter-bloque-disque',
    'moto-et-scooter-alarme-moto',
    'moto-et-scooter-variateur-scooter',
    'moto-et-scooter-embrayage-scooter',
    'moto-et-scooter-courroie-scooter',
    'moto-et-scooter-galet-scooter',
    'moto-et-scooter-ressort-de-poussee-scooter',
    'moto-et-scooter-cloche-d-embrayage-scooter',
    'moto-et-scooter-carburateur-moto',
    'moto-et-scooter-pot-d-echappement-moto',
    'moto-et-scooter-silencieux-moto',
    'moto-et-scooter-collecteur-moto',
    'moto-et-scooter-kit-piston-moto',
    'moto-et-scooter-segment-moto',
    'moto-et-scooter-cylindre-moto',
    'moto-et-scooter-culasse-moto',
    'moto-et-scooter-vilebrequin-moto',
    'moto-et-scooter-arbre-a-came-moto',
    'moto-et-scooter-soupape-moto',
    'moto-et-scooter-ressort-de-soupape-moto',
    'moto-et-scooter-joint-de-culasse-moto',
    'moto-et-scooter-joint-spy-moto',
    'moto-et-scooter-fourche-moto',
    'moto-et-scooter-amortisseur-moto',
    'moto-et-scooter-bras-oscillant-moto',
    'moto-et-scooter-jante-moto',
    'moto-et-scooter-moyeu-moto',
    'moto-et-scooter-roulement-de-roue-moto',
    'moto-et-scooter-etrier-de-frein-moto'
  ]) as slug,
  'two_wheeler' as icon,
  c.id as parent_id,
  generate_series(1, 71) as display_order,
  true as is_active
FROM categories c
WHERE c.slug = 'moto-et-scooter' AND c.parent_id IS NULL;

-- =============================================
-- VÉRIFICATION
-- =============================================

-- Nombre de sous-catégories par catégorie principale
SELECT 
  c1.name as categorie_principale,
  COUNT(c2.id) as nombre_sous_categories
FROM categories c1
LEFT JOIN categories c2 ON c2.parent_id = c1.id
WHERE c1.parent_id IS NULL
GROUP BY c1.name, c1.display_order
ORDER BY c1.display_order;

-- Totaux
SELECT 
  COUNT(*) FILTER (WHERE parent_id IS NULL) as categories_principales,
  COUNT(*) FILTER (WHERE parent_id IS NOT NULL) as sous_categories,
  COUNT(*) as total
FROM categories;

-- Liste complète (limitée à 50 pour l'affichage)
SELECT 
  c1.name as categorie,
  c2.name as sous_categorie,
  c2.slug,
  c2.display_order
FROM categories c1
INNER JOIN categories c2 ON c2.parent_id = c1.id
ORDER BY c1.display_order, c2.display_order
LIMIT 50;
